#!/usr/bin/env python3
"""Extract the LCS RNG functions verbatim from src/compat.cpp.

The parity harness must test the *real* algorithm, not a hand-copy of it, so the
functions are lifted from the original source at build time. If upstream text
changes, the extraction fails loudly rather than silently drifting.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "src" / "compat.cpp"
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent / "rng_extracted.inc"

WANTED = [
    ("unsigned long r_num()", "r_num"),
    ("long LCSrandom(long max)", "LCSrandom"),
    ("unsigned long r_num2()", "r_num2"),
]


def extract(text, signature):
    start = text.index(signature)
    brace = text.index("{", start)
    depth = 0
    for i in range(brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[start:i + 1]
    raise SystemExit(f"unterminated function: {signature}")


def main():
    text = SRC.read_text(errors="replace")
    if "#define MORERANDOM" in re.sub(r"//.*", "", text + (ROOT / "src" / "includes.h").read_text(errors="replace")):
        raise SystemExit("MORERANDOM is enabled upstream; the RNG is no longer deterministic")
    parts = ["// GENERATED by tools/trace_harness/extract_rng.py from src/compat.cpp -- do not edit.",
             "// Liberal Crime Squad is GPL-2.0-or-later; this extract inherits that license.",
             ""]
    for signature, name in WANTED:
        if signature not in text:
            raise SystemExit(f"signature not found in compat.cpp: {signature}")
        parts.append(extract(text, signature))
        parts.append("")
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT} ({len(parts)} blocks)")


if __name__ == "__main__":
    main()
