class_name SiteDialogueTables

extends RefCounted

## GENERATED by tools/extract_site_dialogue.py from src/sitemode/talk.cpp.

## Original dialogue, kept separate from simulation and RNG.

const FLIRT_CENSORED := [
 "\"[What church do you go to?]\"",
 "\"[Will you marry me?]\"",
 "\"[Do you believe in abstinence education?]\""
]

const FLIRT_LINES := [
 "\"Hey baby, you're kinda ugly.  I like that.\"",
 "\"I lost my phone number.  Could I have yours?\"",
 "\"Hey, you wanna go rub one off?\"",
 "\"Hot damn.  You're built like a brick shithouse, honey.\"",
 "\"I know I've seen you on the back of a milk carton, cuz you've been missing from my life.\"",
 "\"I'm big where it counts.\"",
 "\"Daaaaaamn girl, I want to wrap your legs around my face and wear you like a feed bag!\"",
 "\"Let's play squirrel.  I'll bust a nut in your hole.\"",
 "\"You know, if I were you, I'd have sex with me.\"",
 "\"You don't sweat much for a fat chick.\"",
 "\"Fuck me if I'm wrong but you want to kiss me, right?\"",
 "\"Your parents must be retarded, because you are special.\"",
 "\"Let's play trains...  you can sit on my face and I will chew chew chew.\"",
 "\"Is it hot in here or is it just you?\"",
 "\"I may not be Fred Flintstone, but I can make your bed rock!\"",
 "\"What do you say we go behind a rock and get a little boulder?\"",
 "\"Do you have stars on your panties?  Your ass is outta this world!\"",
 "\"Those pants would look great on the floor of my bedroom.\"",
 "\"If I said you had a nice body, would you hold it against me?\"",
 "\"Are you tired?  You've been running around in my thoughts all day.\"",
 "\"If I could change the alphabet baby, I would put the U and I together!\"",
 "\"Your lips look sweet.  Can I taste them?\"",
 "\"Nice shoes.  Wanna fuck?\"",
 "\"Your sexuality makes me nervous and this frustrates me.\"",
 "\"Are you Jamaican?  Cuz Jamaican me horny.\"",
 "\"Hey pop tart, fancy coming in my toaster of love?\"",
 "\"Wanna play army?  You lie down and I'll blow you away.\"",
 "\"Can I lick your forehead?\"",
 "\"I have a genital rash.  Will you rub this ointment on me?\"",
 "\"What's your sign?\"",
 "\"Do you work for the post office? Because I could have sworn you were checking out my package.\"",
 "\"I'm not the most attractive person in here, but I'm the only one talking to you.\"",
 "\"Hi.  I suffer from amnesia.  Do I come here often?\"",
 "\"I'm new in town.  Could you give me directions to your apartment?\"",
 "\"Stand still so I can pick you up!\"",
 "\"Your daddy must have been a baker, cuz you've got a nice set of buns.\"",
 "\"If you were a phaser, you'd be set on 'stunning'.\"",
 "\"Is that a keg in your pants?  Cuz I'd love to tap that ass.\"",
 "\"If I could be anything, I'd love to be your bathwater.\"",
 "\"Stop, drop and roll, baby.  You are on fire.\"",
 "\"Do you want to see something swell?\"",
 "\"Excuse me.  Do you want to fuck or should I apologize?\"",
 "\"Say, did we go to different schools together?\"",
 "\"You smell...  Let's go take a shower.\"",
 "\"Roses are red, violets are blue,All my base, are belong to you.\"",
 "\"Did it hurt when you fell from heaven?\"",
 "\"Holy shit you're hot!  I want to have sex with you RIGHT NOW.\""
]

const DOG_REPLIES := [
 "\"No! Wrong! I'm a dog!! Jesus.\"",
 "\"What?! Ugh, I'm going to toss my kibble.\"",
 "\"Okay, you need to stop petting me now.\""
]

const MONSTER_REPLIES := [
 "\"Foolish human!\"",
 "\"Never thought I'd hear that...\"",
 "\"STRANGER DANGER.\"",
 "\"I am not laughing, mortal!\"",
 "\"Gag!\"",
 "\"You would make jokes with the likes of me?!\"",
 "\"I am above such mortal sins!\"",
 "\"You foul, disgusting human...!\""
]

const FLIRT_ACCEPT_CENSORED := [
 "\"[I go to your church.]\"",
 "\"[Yes.]\"",
 "\"[Yes.  Yes, I do.]\""
]

const FLIRT_ACCEPT := [
 "\"You're not so cute yourself.  Wanna get a room?\"",
 "\"How sweet!  You can call me tonight...\"",
 "\"You bet, baby.\"",
 "\"He he, I'll let that one slide.  Besides, I like country folk...\"",
 "\"That's sick.  I can do sick tonight.\"",
 "\"Oooo, let me see!\"",
 "\"Wow, looks like I'm going to have to reward creativity tonight!\"",
 "\"Winter's coming.  You'd better bust more than one.\"",
 "\"But you're not, so the pleasure's all mine.\"",
 "\"Just wait until tonight, baby.\"",
 "\"You're wrong.\"",
 "\"I can drool on you if you like it that way.\"",
 "\"Oooo, all aboard baby!\"",
 "\"Not as hot as we'll be tonight you slut.\"",
 "\"Goober.  You wanna hook up tonight?\"",
 "\"Oooo, we should get stoned too!  He he.\"",
 "\"You'll have to whip out your rocket to get some.  Let's do it.\"",
 "\"So would my underwear.\"",
 "\"Yeah, and you're going to repay me tonight.\"",
 "\"Then stop *thinking* about it and come over tonight.\"",
 "\"As long as you put a condom between them, I'm all for it.\"",
 "\"Sure, but you can't use your mouth.\"",
 "\"I hope you don't have a foot fetish, but I'm game.\"",
 "\"My sex could do even more.\"",
 "\"Let me invite you to visit my island paradise.  Tonight.\"",
 "\"Oh, man...  just don't tell anybody I'm seeing you.\"",
 "\"I hope we're shooting blanks, soldier.  I'm out of condoms.\"",
 "\"You can lick all my decals off, baby.\"",
 "\"Only if I'm not allowed to use my hands.\"",
 "\"The one that says 'Open All Night'.\"",
 "\"It looks like a letter bomb to me.  Let me blow it up.\"",
 "\"Hey, I could do better.  But I'm feeling cheap tonight.\"",
 "\"Yeah.  I hope you remember the lube this time.\"",
 "\"But if we use a hotel, you won't get shot by an angry spouse tonight.\"",
 "\"I think you'll appreciate the way I move after tonight.\"",
 "\"They make a yummy bedtime snack.\"",
 "\"Oh..  oh, God.  I can't believe I'm going to date a Trekkie.\"",
 "\"Oh, it isn't safe for you to drive like that.  You'd better stay the night.\"",
 "\"Come over tonight and I can show you what it's like.\"",
 "\"I'll stop, drop and roll if you do it with me.\"",
 "\"I'd rather feel something swell.\"",
 "\"You can apologize later if it isn't any good.\"",
 "\"Yeah, and we tonight can try different positions together.\"",
 "\"Don't you like it dirty?\"",
 "\"It's you!!  Somebody set up us the bomb.  Move 'Zig'.  For great justice.\"",
 "\"Actually I'm a succubus from hell, and you're my next victim.\"",
 "\"Can you wait a couple hours?  I got 6 other people to fuck first.\""
]

const FLIRT_REFUSE_CENSORED := [
 "\"I find your lack of faith disturbing.\"",
 "\"No.  I am your father.\"",
 "\"Don't count on it, slimeball!\""
]

const FLIRT_REFUSE := [
 "\"You're such an asshole!\" <pouts>",
 "\"Sure, here ya go...\" <writes wrong number>",
 "\"I'm.. uh.. waiting for someone.\" <turns away>",
 "\"Go use a real bathroom, ya hick.\" <points towards bathroom>",
 "\"That was a very traumatic incident.\" <cries>",
 "\"You're big everywhere, fatass.\" <laughs>",
 "\"You're disgusting.\" <turns away>",
 "\"You fuck squirrels?\" <looks dumbfounded>",
 "\"So what you're saying is you masturbate a lot.\" <wags finger>",
 "\"You're a pig.\" <turns away>",
 "\"Nice try, but no.\" <sticks out tongue>",
 "\"Are you serious?\" <turns away>",
 "\"You look like a biter.\" <flinches>",
 "\"I'm way outta your league, scumbag.\" <grabs pepper spray>",
 "\"You still watch cartoons?\" <laughs>",
 "\"I hate puns!  You suck at comedy.\" <frowns>",
 "\"Yes, I'm an alien, you inferior Earth scum.\" <reaches for ray gun>",
 "\"Not after I do this.\" <shits pants>",
 "\"Yes, I can't stand liars.\" <crosses flabby arms>",
 "\"I don't remember doing that.\" <looks confused>",
 "\"We got a kindergarten dropout over here!\" <points and laughs>",
 "\"No, I don't want to infect anyone else with herpes.\" <sighs>",
 "\"Stop staring at my feet, you freak!\" <kicks you>",
 "\"You're such a loser.\" <makes L sign on forehead>",
 "\"I'm about to put a voodoo curse on yo ass...\" <starts chanting>",
 "\"I don't approve of your hi-carb diet.\" <starts ranting about nutrition>",
 "\"Go back home to play with your G.I. Joe dolls.\" <scoffs>",
 "\"No, and stop acting like a lost puppy.\" <hisses like a cat>",
 "\"Jesus...\" <turns away>",
 "\"I don't believe in astrology, you ignoramus.\" <blinds you with science>",
 "\"Yes, and it's practically microscopic.\" <puts 2 fingers really close together>",
 "\"My spouse will be here soon to straighten things out.\" <looks for spouse>",
 "\"You're not my type.  I like sane people.\" <turns away>",
 "\"Yes, here you go...\" <writes fake directions>",
 "\"Gotta go!  Bye!\" <squirms away>",
 "\"I don't do anal.\" <puts hands over butt>",
 "\"Hey, look, a UFO!\" <ducks away>",
 "\"Go home, you're drunk.\" <gestures away>",
 "\"At least then you'd be liquidated.\" <stares intently>",
 "\"Laaaame.\" <looks bored>",
 "\"Eew, no, gross.\" <vomits on you>",
 "\"Too late for apologies!\" <slaps you>",
 "\"What an idiot!\" <laughs>",
 "\"Nothing works, I can't help it.\" <starts crying>",
 "\"Hahahahaha!\" <shakes head>",
 "\"Yes, now go away.\" <points to exit>",
 "\"Touch me and you'll regret it.\" <crosses arms>"
]

const FUMBLED := {
 "abortion": [
  "\"Conservatives make women turn to coat hangers.\""
 ],
 "animalresearch": [
  "\"Richard Gere put a gerbil in his butt!\""
 ],
 "policebehavior": [
  "\"[The police are not doing their job very well!]\"",
  "\"The cops suck!\""
 ],
 "privacy": [
  "\"The government, like, knows things about you.\""
 ],
 "deathpenalty": [
  "\"They executed this one dude, and like, his head caught on fire.\""
 ],
 "nuclearpower": [
  "\"Have you seen Godzilla?  Nuclear power is bad, yo.\""
 ],
 "pollution": [
  "\"You wanna look like the Toxic Avenger?  Oppose pollution!\""
 ],
 "labor": [
  "\"Bad people wanna make babies work and stuff.\""
 ],
 "gay": [
  "\"Lots of people don't like homosexuals.\""
 ],
 "corporate": [
  "\"The corporations are putting you down, dude.\""
 ],
 "freespeech": [
  "\"Better watch what you say.  They've got ears everywhere.\""
 ],
 "flagburning": [
  "\"The flag is stupid.\""
 ],
 "tax": [
  "\"Rich people, like, have money, man.\""
 ],
 "guncontrol": [
  "\"People like, think they need lots of guns.\""
 ],
 "women": [
  "\"We need more women!\""
 ],
 "civilrights": [
  "\"Conservatives are all racists!\""
 ],
 "drugs": [
  "\"Dude, the government won't let you do drugs.\""
 ],
 "immigration": [
  "\"They're all trying to keep people out of the country.\""
 ],
 "elections": [
  "\"The politicians are just tools of the corporations!\""
 ],
 "military": [
  "\"Patriots are idiots! Give peace a chance!\""
 ],
 "torture": [
  "\"Torture is bad!\""
 ],
 "prisons": [
  "\"Prisoners don't have freedom!\""
 ]
}

const WON_ISSUE := {
 "abortion": [
  "\"Conservatives don't like abortion.\""
 ],
 "animalresearch": [
  "\"Animals are denied the right to vote.\""
 ],
 "policebehavior": [
  "\"The police are still out there.\""
 ],
 "privacy": [
  "\"The government runs intelligence agencies.\""
 ],
 "deathpenalty": [
  "\"You can go to prison for life for serious crimes.\""
 ],
 "nuclearpower": [
  "\"Some people support legalizing nuclear power.\""
 ],
 "pollution": [
  "\"We're still polluting a little bit.\""
 ],
 "labor": [
  "\"Corporate bosses don't always give in to unions.\""
 ],
 "gay": [
  "\"Not everybody likes gay people.\""
 ],
 "corporate": [
  "\"There are corporations.\""
 ],
 "freespeech": [
  "\"People get mad if you swear a lot in public.\""
 ],
 "flagburning": [
  "\"The flag code says you shouldn't make it into clothing.\""
 ],
 "tax": [
  "\"There's still inequality in this country.\""
 ],
 "guncontrol": [
  "\"We need to repeal the second amendment.\""
 ],
 "women": [
  "\"Some people are sexist.\""
 ],
 "civilrights": [
  "\"I knew some people that were pretty racist.\""
 ],
 "drugs": [
  "\"Drugs are expensive.\""
 ],
 "immigration": [
  "\"All the immigrants, not everybody likes them.\""
 ],
 "elections": [
  "\"Some of these politicians rub me the wrong way.\""
 ],
 "military": [
  "\"We still have a military.\""
 ],
 "torture": [
  "\"Some conservatives support torture.\""
 ],
 "prisons": [
  "\"Prisons still exist.\""
 ]
}

const ARGUMENT := {
 "abortion": [
  "\"The government is systematically trying to rob women of the right ",
  "to control their own destinies.\""
 ],
 "animalresearch": [
  "\"Animals are routinely subjected to inhumane treatment in labs in this",
  "country.\""
 ],
 "policebehavior": [
  "\"The police regularly torture minority suspects during interrogations.\""
 ],
 "privacy": [
  "\"Files are being kept on innocent citizens whose only crime is to ",
  "speak out against a system that is trying to farm them like beasts.\""
 ],
 "deathpenalty": [
  "\"Over thirty innocent people have been executed over the past decade.\""
 ],
 "nuclearpower": [
  "\"Radioactive waste is being stored all over the country, and it poses ",
  "a serious threat to many families, even in this neighborhood.\""
 ],
 "pollution": [
  "\"Industries that stop at nothing to become more profitable are polluting ",
  "the environment in ways that hurt not only humans, but animals too.",
  "the environment in ways that hurt not only animals, but people too."
 ],
 "labor": [
  "\"Have you noticed how people are working more and more hours for less and ",
  "less money?  It's all part of a plan to keep you enslaved, man.\""
 ],
 "gay": [
  "\"Homosexuals are people like anyone else, and yet they are treated in this ",
  "country as if they are deviants fit only for cheap entertainment.\""
 ],
 "corporate": [
  "\"Corporate executives use giant corporations as a means to become parasites ",
  "that suck wealth out of this country and put it into their pockets.\""
 ],
 "freespeech": [
  "\"Protests and demonstrations are regularly and often brutally suppressed in ",
  "this country.  People have to watch what they write -- even what they read.\""
 ],
 "flagburning": [
  "\"Burning a piece of cloth is actually stigmatized in this country. ",
  "You can love freedom and still hate what our government stands for.\""
 ],
 "tax": [
  "\"The tax code has been designed to perpetuate an unjust class ",
  "structure that is keeping you oppressed.\""
 ],
 "guncontrol": [
  "\"We live in such a backwards country right now that people think it's ",
  "a right to walk around with the power to murder at any moment.\""
 ],
 "women": [
  "\"Sexism is still pervasive, in subtle ways, and women make much less ",
  "than they deserve for their labor.\""
 ],
 "civilrights": [
  "\"Despite our progress, this society is still strangled by its continuing ",
  "legacy of racial discrimination and inequality.\""
 ],
 "drugs": [
  "\"The government's drug policy is a mess.  We need to stop filling ",
  "prisons with drug users, and only intervene when people really need help.\""
 ],
 "immigration": [
  "\"Millions of people are doing jobs most folks don't even want, and ",
  "saving their families from poverty, but we just try to kick them out.\""
 ],
 "elections": [
  "\"Political favors are bought and sold for campaign contributions, ",
  "and the voting system enforces two party dominance.\""
 ],
 "military": [
  "\"Take a breath and think about the world we live in, that we're spending ",
  "hundreds of billions on new ways to kill people.  This has to stop!\""
 ],
 "torture": [
  "\"In the name of the war on terror, we've sacrificed our soul by letting ",
  "the government torture and abuse human beings on our behalf.\""
 ],
 "prisons": [
  "\"The prison system doesn't help criminals by providing rehabilitation, so ",
  "when they get released, they mostly become criminals again.\""
 ]
}

const COUNTERARGUMENT := {
 "abortion": [
  "\"Abortion is murder.\""
 ],
 "animalresearch": [
  "\"Don't pretend animals are human.\""
 ],
 "policebehavior": [
  "\"Only criminals have reason to fear police.\""
 ],
 "privacy": [
  "\"National security is important.\""
 ],
 "deathpenalty": [
  "\"Some people deserve to die.\""
 ],
 "nuclearpower": [
  "\"Nuclear power is clean.\""
 ],
 "pollution": [
  "\"It's not that bad.\""
 ],
 "labor": [
  "\"Trust the free market, it hasn't failed us yet.\""
 ],
 "gay": [
  "\"Homosexuality is a sin.\""
 ],
 "corporate": [
  "\"Corporations are part of capitalism.\""
 ],
 "freespeech": [
  "\"Don't be offensive and you'll be fine.\""
 ],
 "flagburning": [
  "\"That flag is the sacred symbol of our country.\""
 ],
 "tax": [
  "\"I want to pay lower taxes.\""
 ],
 "guncontrol": [
  "\"Without guns, we're slaves to the Government.\""
 ],
 "women": [
  "\"Why don't you go burn a bra or something?\""
 ],
 "civilrights": [
  "\"Reverse discrimination is still discrimination.\""
 ],
 "drugs": [
  "\"Drugs are a terrible influence on society.\""
 ],
 "immigration": [
  "\"Immigration undermines our economy and culture.\""
 ],
 "elections": [
  "\"Unregulated campaigning is a matter of free speech.\""
 ],
 "military": [
  "\"The military protects us and enables our way of life.\""
 ],
 "torture": [
  "\"The terrorists would do worse to us.\""
 ],
 "prisons": [
  "\"Criminals deserve what they get in prison.\""
 ]
}

const ACCEPT := [
 [
  "\"Dear me! Is there anything we can do?\""
 ],
 [
  "\"That *is* disturbing!   What can I do?\""
 ],
 [
  "\"Gosh!   Is there anything I can do?\""
 ],
 [
  "\"That's frightening!   What can we do?\""
 ],
 [
  "\"Oh, really?\" ",
  "\"Yeah, really!\""
 ],
 [
  "\"Oh my Science!   We've got to do something!\""
 ],
 [
  "\"Dude... that's like... totally bumming me.\""
 ],
 [
  "\"Gadzooks! Something must be done!\""
 ],
 [
  "\"You got anything to smoke on you?\" ",
  "*cough*"
 ],
 [
  "\"Lawks, I don't think we can allow that.\""
 ]
]

const REBUFF := [
 [
  "\"Get away from me, you hippie.\""
 ],
 [
  "\"My heart aches for humanity.\""
 ],
 [
  "\"I'm sorry, but I think I'm done talking to you.\""
 ],
 [
  "\"Do you need some help finding the exit?\""
 ],
 [
  "\"People like you are the reason I'm on medication.\""
 ],
 [
  "\"Everyone is entitled to be stupid, but you abuse the privilege.\""
 ],
 [
  "\"I don't know what you're on, but I hope it's illegal.\""
 ],
 [
  "\"Don't you have a parole meeting to get to?\""
 ],
 [
  "\"Wow. Why am I talking to you again?\""
 ],
 [
  "\"Were you dropped as a child?\""
 ]
]
