class_name ChaserRules
extends RefCounted
## Who comes after a squad, and in what.
##
## GENERATED by tools/extract_chasers.py from makechasers() in
## src/combat/chase.cpp — do not edit by hand.
##
## The crowd is rolled as sitecrime / &"divisor" + 1, plus &"base",
## capped at &"cap". The types are tried in order and the first whose
## laws hold is the one that turns up.
##
## &"pullover" is whether the squad can surrender to them. Only the
## police will take a surrender, and only while they are still police:
## a responder marked &"no_surrender" takes it away again.


## Site type -> who responds to trouble there.
const BY_SITE: Dictionary = {
	&"*": {&"cars": [&"POLICECAR"], &"divisor": 5, &"base": 1, &"cap": 6, &"pullover": true, &"types": [{&"type": &"CREATURE_DEATHSQUAD", &"laws": [[&"policebehavior", &"==", -2]], &"no_surrender": true}, {&"type": &"CREATURE_GANGUNIT", &"laws": [[&"policebehavior", &"<=", -1]]}, {&"type": &"CREATURE_COP"}]},
	&"business_crackhouse": {&"cars": [&"STATIONWAGON"], &"divisor": 3, &"base": 1, &"cap": 18, &"pullover": false, &"types": [{&"type": &"CREATURE_GANGMEMBER"}]},
	&"corporate_headquarters": {&"cars": [&"SUV", &"JEEP"], &"divisor": 5, &"base": 1, &"cap": 6, &"pullover": false, &"types": [{&"type": &"CREATURE_MERC"}]},
	&"corporate_house": {&"cars": [&"SUV", &"JEEP"], &"divisor": 5, &"base": 1, &"cap": 6, &"pullover": false, &"types": [{&"type": &"CREATURE_MERC"}]},
	&"government_armybase": {&"cars": [&"HMMWV"], &"divisor": 5, &"base": 3, &"cap": 6, &"pullover": false, &"types": [{&"type": &"CREATURE_SOLDIER"}]},
	&"government_intelligencehq": {&"cars": [&"AGENTCAR"], &"divisor": 5, &"base": 1, &"cap": 6, &"pullover": false, &"types": [{&"type": &"CREATURE_AGENT"}]},
	&"government_white_house": {&"cars": [&"AGENTCAR"], &"divisor": 5, &"base": 1, &"cap": 6, &"pullover": false, &"types": [{&"type": &"CREATURE_SECRET_SERVICE"}]},
	&"media_amradio": {&"cars": [&"PICKUP"], &"divisor": 3, &"base": 1, &"cap": 18, &"pullover": false, &"types": [{&"type": &"CREATURE_HICK"}]},
	&"media_cablenews": {&"cars": [&"PICKUP"], &"divisor": 3, &"base": 1, &"cap": 18, &"pullover": false, &"types": [{&"type": &"CREATURE_HICK"}]},
}
