class_name DisguiseRules
extends RefCounted
## Which outfit passes for staff, and where.
##
## GENERATED by tools/extract_disguises.py from hasdisguise() in
## src/sitemode/stealth.cpp — do not edit by hand.
##
## Each rule sets how convincing the outfit is: 1 passes, 2 is a partial
## disguise that halves the roll, 0 gives the game away. Rules are applied
## in order and the last one that matches wins, which is how the original's
## run of ifs behaves.
##
## A value of &"high_security_or_partial" means the site decides: convincing where
## the staff are armed and expected, partial anywhere else.
##
## &"laws" requires every listed law to hold; &"not_laws" requires that
## they do not all hold, which is what the original's else branch means.


## Site type -> rules, for a squad walking in off the street.
const BY_SITE: Dictionary = {
	&"*": [],
	&"business_bank": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_CHEAPSUIT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_EXPENSIVESUIT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_SECURITYUNIFORM", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_POLICEUNIFORM", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_POLICEARMOR", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_DEATHSQUADUNIFORM", &"restricted": true, &"laws": [[&"policebehavior", -2], [&"deathpenalty", -2]], &"value": 1}, {&"armor": &"ARMOR_SWATARMOR", &"restricted": true, &"value": &"high_security_or_partial"}, {&"armor": &"ARMOR_CIVILLIANARMOR", &"restricted": true, &"high_security": true, &"value": 1}],
	&"business_cigarbar": [{&"value": 0}, {&"armor": &"ARMOR_EXPENSIVESUIT", &"value": 1}, {&"armor": &"ARMOR_CHEAPSUIT", &"value": 1}, {&"armor": &"ARMOR_EXPENSIVEDRESS", &"value": 1}, {&"armor": &"ARMOR_CHEAPDRESS", &"value": 1}, {&"armor": &"ARMOR_BLACKSUIT", &"value": 1}, {&"armor": &"ARMOR_BLACKDRESS", &"value": 1}],
	&"corporate_headquarters": [{&"value": 0}, {&"armor": &"ARMOR_EXPENSIVESUIT", &"value": 1}, {&"armor": &"ARMOR_CHEAPSUIT", &"value": 1}, {&"armor": &"ARMOR_SECURITYUNIFORM", &"value": 1}, {&"armor": &"ARMOR_EXPENSIVEDRESS", &"value": 1}, {&"armor": &"ARMOR_CHEAPDRESS", &"value": 1}],
	&"corporate_house": [{&"value": 0}, {&"armor": &"ARMOR_EXPENSIVESUIT", &"value": 1}, {&"armor": &"ARMOR_EXPENSIVEDRESS", &"value": 1}, {&"armor": &"ARMOR_SECURITYUNIFORM", &"value": 1}, {&"armor": &"ARMOR_SERVANTUNIFORM", &"value": 1}, {&"armor": &"ARMOR_MILITARY", &"high_security": true, &"value": 1}, {&"armor": &"ARMOR_ARMYARMOR", &"high_security": true, &"value": 1}, {&"armor": &"ARMOR_SEALSUIT", &"high_security": true, &"value": 1}],
	&"government_armybase": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_MILITARY", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_ARMYARMOR", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_SEALSUIT", &"restricted": true, &"value": 1}],
	&"government_courthouse": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_BLACKROBE", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_BLACKSUIT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_BLACKDRESS", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_CHEAPSUIT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_CHEAPDRESS", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_EXPENSIVESUIT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_EXPENSIVEDRESS", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_POLICEUNIFORM", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_POLICEARMOR", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_DEATHSQUADUNIFORM", &"restricted": true, &"laws": [[&"policebehavior", -2], [&"deathpenalty", -2]], &"value": 1}, {&"armor": &"ARMOR_SWATARMOR", &"restricted": true, &"value": &"high_security_or_partial"}],
	&"government_firestation": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_BUNKERGEAR", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_WORKCLOTHES", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_OVERALLS", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_POLICEUNIFORM", &"restricted": true, &"high_security": true, &"value": 1}, {&"armor": &"ARMOR_POLICEARMOR", &"restricted": true, &"high_security": true, &"value": 1}, {&"armor": &"ARMOR_DEATHSQUADUNIFORM", &"restricted": true, &"high_security": true, &"laws": [[&"policebehavior", -2], [&"deathpenalty", -2]], &"value": 1}, {&"armor": &"ARMOR_SWATARMOR", &"restricted": true, &"high_security": true, &"value": 1}],
	&"government_intelligencehq": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_BLACKSUIT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_BLACKDRESS", &"restricted": true, &"value": 1}],
	&"government_policestation": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_POLICEUNIFORM", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_POLICEARMOR", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_DEATHSQUADUNIFORM", &"restricted": true, &"laws": [[&"policebehavior", -2], [&"deathpenalty", -2]], &"value": 1}, {&"armor": &"ARMOR_SWATARMOR", &"restricted": true, &"value": &"high_security_or_partial"}],
	&"government_prison": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_LABCOAT", &"restricted": true, &"laws": [[&"policebehavior", -2], [&"deathpenalty", -2]], &"value": 1}, {&"armor": &"ARMOR_PRISONGUARD", &"restricted": true, &"not_laws": [[&"policebehavior", -2], [&"deathpenalty", -2]], &"value": 1}, {&"armor": &"ARMOR_PRISONER", &"restricted": true, &"value": 1}],
	&"government_white_house": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_BLACKSUIT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_BLACKDRESS", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_CHEAPSUIT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_CHEAPDRESS", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_EXPENSIVESUIT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_EXPENSIVEDRESS", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_MILITARY", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_ARMYARMOR", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_SEALSUIT", &"restricted": true, &"value": 1}],
	&"industry_nuclear": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_LABCOAT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_SECURITYUNIFORM", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_CIVILLIANARMOR", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_HARDHAT", &"restricted": true, &"value": 1}],
	&"industry_polluter": [{&"value": 0}, {&"armor": &"ARMOR_WORKCLOTHES", &"value": 1}, {&"armor": &"ARMOR_HARDHAT", &"value": 1}, {&"armor": &"ARMOR_SECURITYUNIFORM", &"high_security": true, &"value": 1}],
	&"industry_sweatshop": [{&"value": 0}, {&"naked": true, &"value": 1}, {&"armor": &"ARMOR_SECURITYUNIFORM", &"value": 1}],
	&"industry_warehouse": [{&"value": 1}],
	&"laboratory_cosmetics": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_LABCOAT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_SECURITYUNIFORM", &"restricted": true, &"value": &"high_security_or_partial"}],
	&"laboratory_genetic": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_LABCOAT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_SECURITYUNIFORM", &"restricted": true, &"value": &"high_security_or_partial"}],
	&"media_amradio": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_SECURITYUNIFORM", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_EXPENSIVESUIT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_CHEAPSUIT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_EXPENSIVEDRESS", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_CHEAPDRESS", &"restricted": true, &"value": 1}],
	&"media_cablenews": [{&"restricted": true, &"value": 0}, {&"armor": &"ARMOR_SECURITYUNIFORM", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_EXPENSIVESUIT", &"restricted": true, &"value": 1}, {&"armor": &"ARMOR_EXPENSIVEDRESS", &"restricted": true, &"value": 1}],
	&"residential_apartment": [{&"restricted": true, &"value": 0}],
	&"residential_apartment_upscale": [{&"restricted": true, &"value": 0}],
	&"residential_shelter": [{&"value": 1}],
	&"residential_tenement": [{&"restricted": true, &"value": 0}],
}


## Siege type -> rules, for a squad defending its own safehouse.
const BY_SIEGE: Dictionary = {
	&"ccs": [{&"value": 0}],
	&"cia": [{&"armor": &"ARMOR_BLACKSUIT", &"value": 1}, {&"armor": &"ARMOR_BLACKDRESS", &"value": 1}],
	&"corporate": [{&"armor": &"ARMOR_MILITARY", &"value": 1}, {&"armor": &"ARMOR_ARMYARMOR", &"value": 1}, {&"armor": &"ARMOR_SEALSUIT", &"value": 1}],
	&"firemen": [{&"armor": &"ARMOR_BUNKERGEAR", &"value": 1}],
	&"hicks": [{&"armor": &"ARMOR_CLOTHES", &"value": 2}, {&"armor": &"ARMOR_OVERALLS", &"value": 1}, {&"armor": &"ARMOR_WIFEBEATER", &"value": 1}],
	&"police": [{&"armor": &"ARMOR_SWATARMOR", &"escalation": [&"==", 0], &"value": 1}, {&"armor": &"ARMOR_MILITARY", &"escalation": [&">", 0], &"value": 1}, {&"armor": &"ARMOR_ARMYARMOR", &"escalation": [&">", 0], &"value": 1}, {&"armor": &"ARMOR_SEALSUIT", &"escalation": [&">", 0], &"value": 1}],
}
