class_name SitePlans
extends RefCounted
## Which floor plan each kind of site gets.
##
## GENERATED by tools/extract_site_plans.py from initsite() in
## src/sitemode/sitemap.cpp — do not edit by hand.
##
## A site with a hand-drawn map uses it; anything else is generated from a
## plan in core/site_maps.gd. A few types have neither and are built by the
## fallback in core/systems/site/site_builder.gd.


## Site type -> the name of its drawn plan in data/sitemaps/.
const DRAWN: Dictionary = {
	&"business_bank": &"Bank",
	&"business_barandgrill": &"BarAndGrill",
	&"business_cigarbar": &"CigarBar",
	&"business_crackhouse": &"CrackHouse",
	&"business_internetcafe": &"InternetCafe",
	&"business_juicebar": &"JuiceBar",
	&"business_lattestand": &"LatteStand",
	&"business_vegancoop": &"VeganCoOp",
	&"corporate_headquarters": &"CorporateHQ",
	&"corporate_house": &"CEOHouse",
	&"government_armybase": &"ArmyBase",
	&"government_courthouse": &"Courthouse",
	&"government_firestation": &"FireStation",
	&"government_intelligencehq": &"IntelligenceHQ",
	&"government_policestation": &"PoliceStation",
	&"government_prison": &"Prison",
	&"government_white_house": &"WhiteHouse",
	&"industry_nuclear": &"NuclearPlant",
	&"industry_polluter": &"Factory",
	&"industry_sweatshop": &"Sweatshop",
	&"industry_warehouse": &"Warehouse",
	&"laboratory_cosmetics": &"CosmeticsLab",
	&"laboratory_genetic": &"GeneticsLab",
	&"media_amradio": &"RadioStation",
	&"media_cablenews": &"CableNews",
	&"outdoor_bunker": &"Bunker",
	&"outdoor_publicpark": &"Park",
	&"residential_apartment": &"ApartmentUniversity",
	&"residential_apartment_upscale": &"ApartmentDowntown",
	&"residential_bombshelter": &"BombShelter",
	&"residential_shelter": &"HomelessShelter",
	&"residential_tenement": &"ApartmentIndustrial",
}


## Site type -> the plan in core/site_maps.gd that generates it.
const GENERATED: Dictionary = {
	&"business_bank": &"GENERIC_LOBBY",
	&"business_barandgrill": &"GENERIC_LOBBY",
	&"business_cigarbar": &"BUSINESS_RESTRICTEDCAFE",
	&"business_crackhouse": &"GENERIC_UNSECURE",
	&"business_internetcafe": &"BUSINESS_INTERNETCAFE",
	&"business_juicebar": &"BUSINESS_CAFE",
	&"business_lattestand": &"OUTDOOR_LATTESTAND",
	&"business_vegancoop": &"GENERIC_ONEROOM",
	&"corporate_headquarters": &"CORPORATE_HEADQUARTERS",
	&"corporate_house": &"CORPORATE_HOUSE",
	&"government_armybase": &"GOVERNMENT_ARMYBASE",
	&"government_courthouse": &"GOVERNMENT_COURTHOUSE",
	&"government_firestation": &"GENERIC_LOBBY",
	&"government_intelligencehq": &"GOVERNMENT_INTELLIGENCEHQ",
	&"government_policestation": &"GOVERNMENT_POLICESTATION",
	&"government_prison": &"GOVERNMENT_PRISON",
	&"government_white_house": &"GOVERNMENT_WHITE_HOUSE",
	&"industry_nuclear": &"INDUSTRY_NUCLEAR",
	&"industry_polluter": &"INDUSTRY_POLLUTER",
	&"industry_sweatshop": &"INDUSTRY_SWEATSHOP",
	&"industry_warehouse": &"GENERIC_UNSECURE",
	&"laboratory_cosmetics": &"LABORATORY_COSMETICS",
	&"laboratory_genetic": &"LABORATORY_GENETICS",
	&"media_amradio": &"MEDIA_AMRADIO",
	&"media_cablenews": &"MEDIA_CABLENEWS",
	&"outdoor_bunker": &"GENERIC_LOBBY",
	&"outdoor_publicpark": &"OUTDOOR_PUBLICPARK",
	&"residential_apartment": &"RESIDENTIAL_APARTMENT",
	&"residential_apartment_upscale": &"RESIDENTIAL_APARTMENT",
	&"residential_bombshelter": &"GENERIC_LOBBY",
	&"residential_shelter": &"GENERIC_UNSECURE",
	&"residential_tenement": &"RESIDENTIAL_APARTMENT",
}
