class_name SiteMaps
extends RefCounted
## Every floor plan the game can build.
##
## GENERATED by tools/extract_sitemaps.py from art/sitemaps.txt, which is a
## small declarative language: a plan names itself, optionally inherits
## another, then lays down tiles, runs generators, and places specials.
##
## Order is load-bearing: steps are applied in sequence and later ones paint
## over earlier ones.


## Plan name -> {parent, steps}.
const PLANS: Dictionary = {
	&"GENERIC_FRONTDOOR": {
		"parent": &"",
		"steps": [
			{"kind": &"tile", "value": &"OUTDOOR", "params": {&"xstart": "-1", &"xend": "1", &"ystart": "0", &"yend": "1", &"zstart": "0", &"zend": "0"}},
			{"kind": &"tile", "value": &"EXIT", "params": {&"xstart": "-1", &"xend": "1", &"ystart": "0", &"yend": "1", &"zstart": "0", &"zend": "0", &"note": "ADD"}},
			{"kind": &"tile", "value": &"OUTDOOR", "params": {&"x": "0", &"y": "1", &"z": "0"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "0", &"y": "2", &"z": "0"}},
		],
	},
	&"GENERIC_UNSECURE": {
		"parent": &"GENERIC_FRONTDOOR",
		"steps": [
			{"kind": &"script", "value": &"ROOM", "params": {&"xstart": "-12", &"xend": "12", &"ystart": "3", &"yend": "15", &"zstart": "0", &"zend": "0"}},
		],
	},
	&"GENERIC_SECURE": {
		"parent": &"GENERIC_UNSECURE",
		"steps": [
			{"kind": &"tile", "value": &"RESTRICTED", "params": {&"xstart": "-12", &"xend": "12", &"ystart": "2", &"yend": "15", &"zstart": "0", &"zend": "0", &"note": "ADD"}},
		],
	},
	&"GENERIC_ONEROOM": {
		"parent": &"GENERIC_FRONTDOOR",
		"steps": [
			{"kind": &"tile", "value": &"OPEN", "params": {&"xstart": "-4", &"xend": "4", &"ystart": "3", &"yend": "10", &"zstart": "0", &"zend": "0"}},
		],
	},
	&"BUSINESS_CAFE": {
		"parent": &"GENERIC_ONEROOM",
		"steps": [
			{"kind": &"special", "value": &"RESTAURANT_TABLE", "special": 20, "params": {&"xstart": "-4", &"xend": "4", &"ystart": "3", &"yend": "10", &"zstart": "0", &"zend": "0", &"freq": "10"}},
		],
	},
	&"BUSINESS_INTERNETCAFE": {
		"parent": &"BUSINESS_CAFE",
		"steps": [
			{"kind": &"special", "value": &"CAFE_COMPUTER", "special": 21, "params": {&"xstart": "-4", &"xend": "4", &"ystart": "3", &"yend": "10", &"zstart": "0", &"zend": "0", &"freq": "10"}},
		],
	},
	&"BUSINESS_RESTRICTEDCAFE": {
		"parent": &"BUSINESS_CAFE",
		"steps": [
			{"kind": &"special", "value": &"CLUB_BOUNCER", "special": 25, "params": {&"x": "0", &"y": "1", &"z": "0"}},
			{"kind": &"tile", "value": &"RESTRICTED", "params": {&"xstart": "-4", &"xend": "4", &"ystart": "3", &"yend": "10", &"zstart": "0", &"zend": "0"}},
		],
	},
	&"INDUSTRY_SWEATSHOP": {
		"parent": &"GENERIC_SECURE",
		"steps": [
			{"kind": &"special", "value": &"SWEATSHOP_EQUIPMENT", "special": 10, "params": {&"xstart": "-12", &"xend": "12", &"ystart": "3", &"yend": "15", &"zstart": "0", &"zend": "0", &"freq": "10"}},
			{"kind": &"loot", "value": &"FINECLOTH", "params": {&"weight": "100"}},
		],
	},
	&"INDUSTRY_POLLUTER": {
		"parent": &"GENERIC_SECURE",
		"steps": [
			{"kind": &"special", "value": &"POLLUTER_EQUIPMENT", "special": 11, "params": {&"xstart": "-12", &"xend": "12", &"ystart": "3", &"yend": "15", &"zstart": "0", &"zend": "0", &"freq": "10"}},
			{"kind": &"loot", "value": &"CHEMICAL", "params": {&"weight": "100"}},
		],
	},
	&"INDUSTRY_NUCLEAR": {
		"parent": &"GENERIC_SECURE",
		"steps": [
			{"kind": &"unique", "value": &"NUCLEAR_ONOFF", "special": 12, "params": {}},
		],
	},
	&"GOVERNMENT_INTELLIGENCEHQ": {
		"parent": &"GENERIC_SECURE",
		"steps": [
			{"kind": &"unique", "value": &"INTEL_SUPERCOMPUTER", "special": 9, "params": {}},
		],
	},
	&"CORPORATE_HEADQUARTERS": {
		"parent": &"GENERIC_SECURE",
		"steps": [
			{"kind": &"unique", "value": &"CORPORATE_FILES", "special": 15, "params": {}},
		],
	},
	&"CORPORATE_HOUSE": {
		"parent": &"GENERIC_FRONTDOOR",
		"steps": [
			{"kind": &"tile", "value": &"GRASSY", "params": {&"x": "-1", &"y": "2"}},
			{"kind": &"tile", "value": &"GRASSY", "params": {&"x": "1", &"y": "2"}},
			{"kind": &"tile", "value": &"EXIT", "params": {&"x": "-2", &"ystart": "0", &"yend": "1"}},
			{"kind": &"tile", "value": &"EXIT", "params": {&"x": "2", &"ystart": "0", &"yend": "1"}},
			{"kind": &"tile", "value": &"OPEN", "params": {&"x": "0", &"ystart": "3", &"yend": "5"}},
			{"kind": &"tile", "value": &"OPEN", "params": {&"xstart": "-5", &"xend": "0", &"y": "4"}},
			{"kind": &"tile", "value": &"OPEN", "params": {&"xstart": "-8", &"xend": "-6", &"ystart": "3", &"yend": "5"}},
			{"kind": &"tile", "value": &"GRASSY", "params": {&"xstart": "-4", &"xend": "-1", &"y": "3"}},
			{"kind": &"tile", "value": &"GRASSY", "params": {&"xstart": "-4", &"xend": "-2", &"y": "5"}},
			{"kind": &"tile", "value": &"GRASSY", "params": {&"xstart": "1", &"xend": "4", &"ystart": "3", &"yend": "4"}},
			{"kind": &"tile", "value": &"GRASSY", "params": {&"xstart": "2", &"xend": "4", &"y": "5"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "-7", &"y": "6"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "0", &"y": "6"}},
			{"kind": &"tile", "value": &"OPEN", "params": {&"xstart": "-8", &"xend": "-4", &"ystart": "7", &"yend": "9"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "-3", &"y": "8"}},
			{"kind": &"tile", "value": &"OPEN", "params": {&"xstart": "-2", &"xend": "2", &"ystart": "7", &"yend": "9"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "3", &"y": "8"}},
			{"kind": &"tile", "value": &"OPEN", "params": {&"xstart": "4", &"xend": "8", &"ystart": "7", &"yend": "9"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "7", &"y": "6"}},
			{"kind": &"tile", "value": &"OPEN", "params": {&"xstart": "6", &"xend": "8", &"ystart": "3", &"yend": "5"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "-7", &"y": "10"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "7", &"y": "10"}},
			{"kind": &"tile", "value": &"RESTRICTED", "params": {&"xstart": "-10", &"xend": "10", &"ystart": "6", &"yend": "10", &"note": "ADD"}},
			{"kind": &"tile", "value": &"RESTRICTED", "params": {&"xstart": "5", &"xend": "9", &"ystart": "2", &"yend": "6", &"note": "ADD"}},
			{"kind": &"script", "value": &"ROOM", "params": {&"xstart": "-12", &"xend": "-5", &"ystart": "11", &"yend": "16"}},
			{"kind": &"script", "value": &"ROOM", "params": {&"xstart": "6", &"xend": "13", &"ystart": "11", &"yend": "16"}},
			{"kind": &"tile", "value": &"RESTRICTED", "params": {&"xstart": "-13", &"xend": "-5", &"ystart": "10", &"yend": "17", &"note": "ADD"}},
			{"kind": &"tile", "value": &"RESTRICTED", "params": {&"xstart": "5", &"xend": "13", &"ystart": "10", &"yend": "17", &"note": "ADD"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "-5", &"y": "12"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "5", &"y": "12"}},
			{"kind": &"tile", "value": &"OPEN", "params": {&"xstart": "-4", &"xend": "4", &"y": "12"}},
			{"kind": &"tile", "value": &"GRASSY", "params": {&"xstart": "-4", &"xend": "4", &"y": "11"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "0", &"y": "13"}},
			{"kind": &"script", "value": &"ROOM", "params": {&"xstart": "-4", &"xend": "5", &"ystart": "14", &"yend": "19"}},
			{"kind": &"tile", "value": &"OUTDOOR", "params": {&"xstart": "-4", &"xend": "4", &"ystart": "3", &"yend": "5", &"note": "ADD"}},
			{"kind": &"tile", "value": &"OUTDOOR", "params": {&"xstart": "-4", &"yend": "12", &"ystart": "11", &"note": "ADD"}},
			{"kind": &"tile", "value": &"RESTRICTED", "params": {&"xstart": "-4", &"xend": "4", &"ystart": "13", &"yend": "18", &"note": "ADD"}},
			{"kind": &"unique", "value": &"HOUSE_PHOTOS", "special": 13, "params": {}},
			{"kind": &"unique", "value": &"HOUSE_CEO", "special": 14, "params": {}},
		],
	},
	&"GOVERNMENT_ARMYBASE": {
		"parent": &"GENERIC_FRONTDOOR",
		"steps": [
			{"kind": &"tile", "value": &"GRASSY", "params": {&"xstart": "-20", &"xend": "20", &"ystart": "3", &"yend": "4"}},
			{"kind": &"tile", "value": &"GRASSY", "params": {&"xstart": "-8", &"xend": "8", &"ystart": "5", &"yend": "6"}},
			{"kind": &"script", "value": &"ROOM", "params": {&"xstart": "-28", &"xend": "-21", &"ystart": "3", &"yend": "11"}},
			{"kind": &"script", "value": &"ROOM", "params": {&"xstart": "-20", &"xend": "-9", &"ystart": "6", &"yend": "11"}},
			{"kind": &"script", "value": &"ROOM", "params": {&"xstart": "-8", &"xend": "9", &"ystart": "8", &"yend": "11"}},
			{"kind": &"script", "value": &"ROOM", "params": {&"xstart": "22", &"xend": "29", &"ystart": "3", &"yend": "11"}},
			{"kind": &"script", "value": &"ROOM", "params": {&"xstart": "10", &"xend": "21", &"ystart": "6", &"yend": "11"}},
			{"kind": &"script", "value": &"ROOM", "params": {&"xstart": "-20", &"xend": "21", &"ystart": "12", &"yend": "20"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "-21", &"y": "4"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "21", &"y": "4"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "-21", &"y": "9"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "21", &"y": "9"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "-9", &"y": "9"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "9", &"y": "9"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "-1", &"y": "7"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "1", &"y": "7"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "-16", &"y": "11"}},
			{"kind": &"tile", "value": &"DOOR", "params": {&"x": "16", &"y": "11"}},
			{"kind": &"tile", "value": &"RESTRICTED", "params": {&"xstart": "-28", &"xend": "28", &"ystart": "3", &"yend": "19", &"note": "ADD"}},
			{"kind": &"unique", "value": &"ARMYBASE_ARMORY", "special": 27, "params": {}},
		],
	},
	&"LABORATORY_GENETICS": {
		"parent": &"GENERIC_SECURE",
		"steps": [
			{"kind": &"special", "value": &"LAB_GENETIC_CAGEDANIMALS", "special": 1, "params": {&"xstart": "-12", &"xend": "12", &"ystart": "3", &"yend": "15", &"zstart": "0", &"zend": "0", &"freq": "10"}},
		],
	},
	&"LABORATORY_COSMETICS": {
		"parent": &"GENERIC_SECURE",
		"steps": [
			{"kind": &"special", "value": &"LAB_COSMETICS_CAGEDANIMALS", "special": 0, "params": {&"xstart": "-12", &"xend": "12", &"ystart": "3", &"yend": "15", &"zstart": "0", &"zend": "0", &"freq": "10"}},
		],
	},
	&"GENERIC_LOBBY": {
		"parent": &"GENERIC_SECURE",
		"steps": [
			{"kind": &"tile", "value": &"OPEN", "params": {&"x": "0", &"y": "3", &"z": "0"}},
		],
	},
	&"GOVERNMENT_POLICESTATION": {
		"parent": &"GENERIC_LOBBY",
		"steps": [
			{"kind": &"unique", "value": &"POLICESTATION_LOCKUP", "special": 2, "params": {}},
		],
	},
	&"GOVERNMENT_COURTHOUSE": {
		"parent": &"GENERIC_LOBBY",
		"steps": [
			{"kind": &"unique", "value": &"COURTHOUSE_LOCKUP", "special": 3, "params": {}},
			{"kind": &"unique", "value": &"COURTHOUSE_JURYROOM", "special": 4, "params": {}},
		],
	},
	&"GOVERNMENT_PRISON": {
		"parent": &"GENERIC_LOBBY",
		"steps": [
			{"kind": &"unique", "value": &"PRISON_CONTROL_LOW", "special": 6, "params": {}},
			{"kind": &"script", "value": &"ROOM", "params": {&"xstart": "-12", &"xend": "12", &"ystart": "3", &"yend": "15", &"zstart": "1", &"zend": "2"}},
			{"kind": &"tile", "value": &"RESTRICTED", "params": {&"xstart": "-28", &"xend": "28", &"ystart": "3", &"yend": "19", &"zstart": "1", &"zend": "2", &"note": "ADD"}},
			{"kind": &"unique", "value": &"PRISON_CONTROL_MEDIUM", "special": 7, "params": {&"z": "1"}},
			{"kind": &"unique", "value": &"PRISON_CONTROL_HIGH", "special": 8, "params": {&"z": "2"}},
			{"kind": &"script", "value": &"STAIRS_RANDOM", "params": {&"xstart": "-28", &"xend": "28", &"ystart": "3", &"yend": "19", &"zstart": "0", &"zend": "2"}},
		],
	},
	&"MEDIA_AMRADIO": {
		"parent": &"GENERIC_SECURE",
		"steps": [
			{"kind": &"unique", "value": &"RADIO_BROADCASTSTUDIO", "special": 16, "params": {}},
		],
	},
	&"MEDIA_CABLENEWS": {
		"parent": &"GENERIC_SECURE",
		"steps": [
			{"kind": &"unique", "value": &"NEWS_BROADCASTSTUDIO", "special": 17, "params": {}},
		],
	},
	&"RESIDENTIAL_APARTMENT": {
		"parent": &"GENERIC_FRONTDOOR",
		"steps": [
			{"kind": &"tile", "value": &"OPEN", "params": {}},
			{"kind": &"script", "value": &"HALLWAY_YAXIS", "params": {&"xstart": "0", &"xend": "7", &"ystart": "3", &"yend": "18", &"zstart": "0", &"zend": "6"}},
			{"kind": &"tile", "value": &"OPEN", "params": {&"x": "0", &"ystart": "18", &"yend": "19", &"zstart": "0", &"zend": "6"}},
			{"kind": &"script", "value": &"STAIRS", "params": {&"xstart": "-1", &"xend": "1", &"ystart": "19", &"yend": "19", &"zstart": "0", &"zend": "6"}},
			{"kind": &"tile", "value": &"RESTRICTED", "params": {&"xstart": "-9", &"xend": "-1", &"ystart": "3", &"yend": "18", &"zstart": "0", &"zend": "6", &"note": "ADD"}},
			{"kind": &"tile", "value": &"RESTRICTED", "params": {&"xstart": "1", &"xend": "9", &"ystart": "6", &"yend": "18", &"zstart": "0", &"zend": "0", &"note": "ADD"}},
			{"kind": &"tile", "value": &"RESTRICTED", "params": {&"xstart": "1", &"xend": "9", &"ystart": "3", &"yend": "18", &"zstart": "1", &"zend": "6", &"note": "ADD"}},
			{"kind": &"special", "value": &"APARTMENT_LANDLORD", "special": 18, "params": {&"x": "2", &"y": "5", &"z": "0"}},
			{"kind": &"special", "value": &"APARTMENT_SIGN", "special": 19, "params": {&"x": "0", &"y": "2", &"z": "0"}},
		],
	},
	&"OUTDOOR_OPEN": {
		"parent": &"",
		"steps": [
			{"kind": &"tile", "value": &"EXIT", "params": {&"xstart": "-3", &"xend": "3", &"ystart": "0", &"yend": "6", &"zstart": "0", &"zend": "0"}},
			{"kind": &"tile", "value": &"OUTDOOR", "params": {&"xstart": "-2", &"xend": "2", &"ystart": "1", &"yend": "5", &"zstart": "0", &"zend": "0"}},
		],
	},
	&"OUTDOOR_PUBLICPARK": {
		"parent": &"",
		"steps": [
			{"kind": &"tile", "value": &"EXIT", "params": {&"xstart": "-5", &"xend": "5", &"ystart": "0", &"yend": "10"}},
			{"kind": &"tile", "value": &"OUTDOOR", "params": {&"xstart": "-4", &"xend": "4", &"ystart": "1", &"yend": "9"}},
			{"kind": &"tile", "value": &"GRASSY", "params": {&"xstart": "-3", &"xend": "-1", &"ystart": "2", &"yend": "4", &"note": "ADD"}},
			{"kind": &"tile", "value": &"GRASSY", "params": {&"xstart": "1", &"xend": "3", &"ystart": "2", &"yend": "4", &"note": "ADD"}},
			{"kind": &"tile", "value": &"GRASSY", "params": {&"xstart": "1", &"xend": "3", &"ystart": "6", &"yend": "8", &"note": "ADD"}},
			{"kind": &"tile", "value": &"GRASSY", "params": {&"xstart": "-3", &"xend": "-1", &"ystart": "6", &"yend": "8", &"note": "ADD"}},
			{"kind": &"tile", "value": &"BLOCK", "params": {&"xstart": "-4", &"xend": "-1", &"y": "1"}},
			{"kind": &"tile", "value": &"BLOCK", "params": {&"xstart": "1", &"xend": "4", &"y": "1"}},
			{"kind": &"tile", "value": &"BLOCK", "params": {&"xstart": "-4", &"xend": "-1", &"y": "9"}},
			{"kind": &"tile", "value": &"BLOCK", "params": {&"xstart": "1", &"xend": "4", &"y": "9"}},
			{"kind": &"tile", "value": &"BLOCK", "params": {&"x": "-4", &"ystart": "2", &"yend": "4"}},
			{"kind": &"tile", "value": &"BLOCK", "params": {&"x": "4", &"ystart": "2", &"yend": "4"}},
			{"kind": &"tile", "value": &"BLOCK", "params": {&"x": "-4", &"ystart": "6", &"yend": "8"}},
			{"kind": &"tile", "value": &"BLOCK", "params": {&"x": "4", &"ystart": "6", &"yend": "8"}},
		],
	},
	&"OUTDOOR_LATTESTAND": {
		"parent": &"OUTDOOR_OPEN",
		"steps": [
			{"kind": &"special", "value": &"RESTAURANT_TABLE", "special": 20, "params": {&"xstart": "-2", &"xend": "2", &"ystart": "1", &"yend": "5", &"zstart": "0", &"zend": "0", &"freq": "10"}},
		],
	},
}
