class_name SleeperRules
extends RefCounted
## What a sleeper is worth to the cause, by what they do for a living.
##
## Generated by tools/extract_sleeper_influence.py from sleeper_influence() in
## src/monthly/sleeper_update.cpp. Do not edit by hand.
##
## The original writes this as three switches that lean on C's fall-through — a
## judge collects the lawyer's issues on top of their own, an eminent scientist
## collects the lab tech's — so the tables below have the fall-through already
## resolved. Four professions do something no table can describe and are
## handled in code: a radio host and a news anchor subvert their own station, a
## politician picks three issues at random, and a firefighter only has an
## opinion where free speech has been outlawed.

## The skill each profession adds to its base power, in the order the
## original adds them.
const PROFESSIONAL_SKILL := {
	&"CREATURE_AUTHOR": [&"writing"],
	&"CREATURE_CORPORATE_CEO": [&"business"],
	&"CREATURE_CORPORATE_MANAGER": [&"business"],
	&"CREATURE_CRITIC_ART": [&"writing", &"art"],
	&"CREATURE_CRITIC_MUSIC": [&"writing", &"music"],
	&"CREATURE_EDUCATOR": [&"psychology"],
	&"CREATURE_JOURNALIST": [&"writing"],
	&"CREATURE_JUDGE_CONSERVATIVE": [&"writing", &"law"],
	&"CREATURE_LAWYER": [&"law"],
	&"CREATURE_MUSICIAN": [&"music"],
	&"CREATURE_NUN": [&"religion"],
	&"CREATURE_PAINTER": [&"art"],
	&"CREATURE_PRIEST": [&"religion"],
	&"CREATURE_SCIENTIST_EMINENT": [&"science"],
	&"CREATURE_SCIENTIST_LABTECH": [&"science"],
	&"CREATURE_SCULPTOR": [&"art"],
}

## How much each profession's word is worth. Everybody not listed
## doubles, which is what the switch's default case does.
const WORTH := {
	&"CREATURE_ACTOR": 4,
	&"CREATURE_CORPORATE_CEO": 20,
	&"CREATURE_DEATHSQUAD": 6,
	&"CREATURE_EDUCATOR": 6,
	&"CREATURE_GANGUNIT": 4,
	&"CREATURE_MILITARYOFFICER": 6,
	&"CREATURE_MILITARYPOLICE": 4,
	&"CREATURE_POLITICIAN": 20,
	&"CREATURE_SCIENTIST_EMINENT": 20,
	&"CREATURE_SEAL": 4,
}

## What a profession the table does not name is worth.
const DEFAULT_WORTH := 2

## The issues each profession gets to talk about. A profession not
## listed here influences one issue at random.
const ISSUES := {
	&"CREATURE_ACTOR": [&"women", &"civilrights", &"gay", &"freespeech", &"drugs", &"immigration"],
	&"CREATURE_AGENT": [&"intelligence", &"torture", &"prisons", &"freespeech"],
	&"CREATURE_AUTHOR": [&"women", &"civilrights", &"gay", &"freespeech", &"drugs", &"immigration"],
	&"CREATURE_COP": [&"policebehavior", &"drugs", &"torture", &"guncontrol", &"prisons"],
	&"CREATURE_CORPORATE_CEO": [&"ceosalary", &"women", &"taxes", &"corporateculture", &"sweatshops", &"pollution", &"civilrights"],
	&"CREATURE_CORPORATE_MANAGER": [&"women", &"taxes", &"corporateculture", &"sweatshops", &"pollution", &"civilrights"],
	&"CREATURE_CRITIC_ART": [&"women", &"civilrights", &"gay", &"freespeech", &"drugs", &"immigration"],
	&"CREATURE_CRITIC_MUSIC": [&"women", &"civilrights", &"gay", &"freespeech", &"drugs", &"immigration"],
	&"CREATURE_DEATHSQUAD": [&"prisons", &"deathpenalty", &"policebehavior", &"drugs", &"torture", &"guncontrol", &"prisons"],
	&"CREATURE_EDUCATOR": [&"policebehavior", &"deathpenalty", &"drugs", &"torture", &"prisons"],
	&"CREATURE_GANGUNIT": [&"policebehavior", &"drugs", &"torture", &"guncontrol", &"prisons"],
	&"CREATURE_JOURNALIST": [&"women", &"civilrights", &"gay", &"freespeech", &"drugs", &"immigration"],
	&"CREATURE_JUDGE_CONSERVATIVE": [&"justices", &"freespeech", &"intelligence", &"policebehavior", &"deathpenalty", &"guncontrol", &"drugs"],
	&"CREATURE_LAWYER": [&"policebehavior", &"deathpenalty", &"guncontrol", &"drugs"],
	&"CREATURE_MERC": [&"guncontrol"],
	&"CREATURE_MILITARYOFFICER": [&"military", &"torture", &"gay", &"women"],
	&"CREATURE_MILITARYPOLICE": [&"military", &"torture", &"gay", &"women"],
	&"CREATURE_MUSICIAN": [&"women", &"civilrights", &"gay", &"freespeech", &"drugs", &"immigration"],
	&"CREATURE_PAINTER": [&"women", &"civilrights", &"gay", &"freespeech", &"drugs", &"immigration"],
	&"CREATURE_PRIEST": [&"women", &"civilrights", &"gay", &"freespeech", &"drugs", &"immigration"],
	&"CREATURE_PRISONER": [&"policebehavior", &"deathpenalty", &"drugs", &"torture", &"prisons"],
	&"CREATURE_PRISONGUARD": [&"policebehavior", &"deathpenalty", &"drugs", &"torture", &"prisons"],
	&"CREATURE_PSYCHOLOGIST": [&"women", &"civilrights", &"gay", &"freespeech", &"drugs", &"immigration"],
	&"CREATURE_SCIENTIST_EMINENT": [&"pollution", &"nuclearpower", &"animalresearch", &"genetics"],
	&"CREATURE_SCIENTIST_LABTECH": [&"nuclearpower", &"animalresearch", &"genetics"],
	&"CREATURE_SCULPTOR": [&"women", &"civilrights", &"gay", &"freespeech", &"drugs", &"immigration"],
	&"CREATURE_SEAL": [&"military", &"torture", &"gay", &"women"],
	&"CREATURE_SECRET_SERVICE": [&"intelligence"],
	&"CREATURE_SOLDIER": [&"military", &"torture", &"gay", &"women"],
	&"CREATURE_SWAT": [&"policebehavior", &"drugs", &"torture", &"guncontrol", &"prisons"],
	&"CREATURE_VETERAN": [&"military", &"torture", &"gay", &"women"],
	&"CREATURE_WORKER_SWEATSHOP": [&"immigration", &"sweatshops"],
}

## Professions with nothing to offer: already Liberal, or
## in no position to do any good at all.
const HARMLESS: Array[StringName] = [
	&"CREATURE_BUM",
	&"CREATURE_CRACKHEAD",
	&"CREATURE_GENETIC",
	&"CREATURE_GUARDDOG",
	&"CREATURE_HIPPIE",
	&"CREATURE_JUDGE_LIBERAL",
	&"CREATURE_MUTANT",
	&"CREATURE_TANK",
	&"CREATURE_WORKER_FACTORY_CHILD",
	&"CREATURE_WORKER_FACTORY_UNION",
]
