class_name WorldLayout
extends RefCounted
## The shape of a city: its districts and what stands in each.
##
## GENERATED by tools/extract_world.py from make_classic_world() in
## src/locations/world.cpp, which is written as a declarative block of
## macros — a description of a city, not an algorithm.
##
## Order is load-bearing: locations are numbered as they are created, and
## those ids are what everything else refers to.


## Districts in order, each with the sites it contains.
static func districts(has_maps: bool) -> Array:
	return [
		{
			"type": &"downtown",
			"area": 0,
			"properties": {&"mapped": has_maps},
			"sites": [
				{"type": &"residential_apartment_upscale", "properties": {&"mapped": has_maps}},
				{"type": &"government_policestation", "properties": {&"mapped": has_maps}},
				{"type": &"government_courthouse", "properties": {&"mapped": has_maps}},
				{"type": &"business_bank", "properties": {&"mapped": has_maps}},
				{"type": &"government_firestation", "properties": {&"mapped": has_maps}},
				{"type": &"media_amradio", "properties": {&"mapped": has_maps}},
				{"type": &"media_cablenews", "properties": {&"mapped": has_maps}},
				{"type": &"business_cigarbar", "properties": {&"mapped": has_maps}},
				{"type": &"business_lattestand", "properties": {&"mapped": has_maps}},
				{"type": &"business_barandgrill", "properties": {&"renting": Renting.CCS, &"hidden": true, &"mapped": false}},
			],
		},
		{
			"type": &"commercial",
			"area": 0,
			"properties": {},
			"sites": [
				{"type": &"business_deptstore", "properties": {}},
				{"type": &"business_pawnshop", "properties": {}},
				{"type": &"business_halloween", "properties": {}},
				{"type": &"business_cardealership", "properties": {}},
			],
		},
		{
			"type": &"udistrict",
			"area": 0,
			"properties": {},
			"sites": [
				{"type": &"residential_apartment", "properties": {}},
				{"type": &"hospital_university", "properties": {}},
				{"type": &"hospital_clinic", "properties": {}},
				{"type": &"laboratory_genetic", "properties": {}},
				{"type": &"laboratory_cosmetics", "properties": {}},
				{"type": &"business_vegancoop", "properties": {}},
				{"type": &"business_juicebar", "properties": {}},
				{"type": &"business_internetcafe", "properties": {}},
				{"type": &"outdoor_publicpark", "properties": {}},
			],
		},
		{
			"type": &"industrial",
			"area": 0,
			"properties": {},
			"sites": [
				{"type": &"residential_shelter", "properties": {&"renting": Renting.PERMANENT}},
				{"type": &"industry_warehouse", "properties": {&"renting": Renting.PERMANENT, &"upgradable": true}},
				{"type": &"residential_tenement", "properties": {}},
				{"type": &"industry_polluter", "properties": {}},
				{"type": &"industry_sweatshop", "properties": {}},
				{"type": &"business_crackhouse", "properties": {&"upgradable": true}},
				{"type": &"residential_bombshelter", "properties": {&"renting": Renting.CCS, &"hidden": true}},
			],
		},
		{
			"type": &"outoftown",
			"area": 1,
			"properties": {},
			"sites": [
				{"type": &"government_prison", "properties": {}},
				{"type": &"government_intelligencehq", "properties": {}},
				{"type": &"industry_nuclear", "properties": {}},
				{"type": &"corporate_headquarters", "properties": {}},
				{"type": &"corporate_house", "properties": {}},
				{"type": &"government_armybase", "properties": {}},
				{"type": &"outdoor_bunker", "properties": {&"renting": Renting.CCS, &"hidden": true}},
			],
		},
		{
			"type": &"travel",
			"area": 1,
			"properties": {},
			"sites": [
				{"type": &"government_white_house", "properties": {}},
			],
		},
	]
