#!/usr/bin/env python3
"""Extracts the site map scripts from art/sitemaps.txt.

The file is a small declarative language read by src/configfile.cpp: each
OBJECT SITEMAP names a floor plan, optionally inherits another with USE, and
then lays down tiles, runs generator scripts, and places specials and loot.

Parsed here rather than at runtime because it is content, and because a
generated table is one fewer parser to get right twice.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "art" / "sitemaps.txt"
OUT = ROOT / "game" / "core" / "site_maps.gd"

## Commands that start a new step; anything else configures the current one.
STEP_COMMANDS = {"TILE", "SCRIPT", "SPECIAL", "UNIQUE", "LOOT"}


def read_lines(text):
    for raw in text.splitlines():
        line = raw.replace("\r", "")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        stripped = line.lstrip(" \t")
        parts = stripped.split(None, 1)
        command = parts[0]
        value = parts[1].strip() if len(parts) > 1 else ""
        yield command, value


def main() -> int:
    maps = []
    current = None
    step = None

    for command, value in read_lines(SOURCE.read_text(errors="replace")):
        if command == "OBJECT":
            if value != "SITEMAP":
                raise SystemExit(f"unhandled OBJECT type: {value}")
            current = {"name": "", "parent": "", "steps": []}
            maps.append(current)
            step = None
            continue
        if current is None:
            raise SystemExit(f"{command} before any OBJECT")

        if command == "NAME":
            current["name"] = value
        elif command == "USE":
            current["parent"] = value
        elif command in STEP_COMMANDS:
            step = {"kind": command.lower(), "value": value, "params": {}}
            current["steps"].append(step)
        elif step is not None:
            step["params"][command.lower()] = value
        else:
            raise SystemExit(f"{command} outside any step in {current['name']}")

    lines = [
        "class_name SiteMaps",
        "extends RefCounted",
        "## Every floor plan the game can build.",
        "##",
        "## GENERATED by tools/extract_sitemaps.py from art/sitemaps.txt, which is a",
        "## small declarative language: a plan names itself, optionally inherits",
        "## another, then lays down tiles, runs generators, and places specials.",
        "##",
        "## Order is load-bearing: steps are applied in sequence and later ones paint",
        "## over earlier ones.",
        "",
        "",
        "## Plan name -> {parent, steps}.",
        "const PLANS: Dictionary = {",
    ]
    for entry in maps:
        lines.append(f'\t&"{entry["name"]}": {{')
        lines.append(f'\t\t"parent": &"{entry["parent"]}",')
        lines.append('\t\t"steps": [')
        for step in entry["steps"]:
            params = ", ".join(f'&"{k}": "{v}"' for k, v in step["params"].items())
            lines.append('\t\t\t{"kind": &"%s", "value": &"%s", "params": {%s}},'
                         % (step["kind"], step["value"], params))
        lines.append("\t\t],")
        lines.append("\t},")
    lines += ["}", ""]

    OUT.write_text("\n".join(lines))
    steps = sum(len(entry["steps"]) for entry in maps)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(maps)} plans, {steps} steps")
    return 0


if __name__ == "__main__":
    sys.exit(main())
