#!/usr/bin/env python3
"""Generates game/core/chaser_rules.gd from makechasers().

Who comes after a squad that has just done something depends on where they did
it: soldiers from an army base, agents from an intelligence headquarters, hicks
from a radio station, and the police from anywhere else. The table is a switch
in src/combat/chase.cpp and is read back out rather than transcribed.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "combat" / "chase.cpp"
OUT = ROOT / "game" / "core" / "chaser_rules.gd"


def main() -> int:
    text = SOURCE.read_text(errors="replace")
    start = text.index("void makechasers(long sitetype,long sitecrime)")
    body = text[start:text.index("\n   for(n=0;n<pnum;n++) conservatise", start)]

    responses = {}
    labels = []
    current = None
    for raw in body.splitlines():
        line = re.sub(r"//.*", "", raw).strip()
        case = re.fullmatch(r"case (SITE_[A-Z0-9_]+):", line)
        if case:
            labels.append(case.group(1).removeprefix("SITE_").lower())
            continue
        if line == "default:":
            labels.append("*")
            continue
        if not labels:
            continue

        if current is None:
            current = {"cars": [], "divisor": 5, "base": 1, "cap": 6,
                       "pullover": False, "types": []}

        if re.fullmatch(r"chaseseq\.canpullover=1;", line):
            current["pullover"] = True
        car = re.search(r'cartype="([A-Z0-9_]+)"', line)
        if car:
            current["cars"].append(car.group(1))
        crowd = re.fullmatch(r"pnum=LCSrandom\(sitecrime/(\d+) \+ 1\)\+(\d+);", line)
        if crowd:
            current["divisor"] = int(crowd.group(1))
            current["base"] = int(crowd.group(2))
        cap = re.fullmatch(r"if\(pnum>(\d+)\)\s*pnum=(\d+);", line.replace(" ", " "))
        if cap:
            current["cap"] = int(cap.group(1))
        spawn = re.search(r"makecreature\(encounter\[encslot\+\+\],(CREATURE_[A-Z0-9_]+)\)", line)
        if spawn:
            rule = {"type": spawn.group(1)}
            laws = re.findall(r"law\[LAW_([A-Z0-9_]+)\](==|<=|>=|<|>)(-?\d+)", line)
            if laws:
                rule["laws"] = laws
            if "chaseseq.canpullover=0" in line:
                rule["no_surrender"] = True
            current["types"].append(rule)
        if line == "break;" and labels:
            for label in labels:
                responses[label] = current
            labels = []
            current = None

    if not responses:
        raise SystemExit("no chaser responses found")

    lines = [
        "class_name ChaserRules",
        "extends RefCounted",
        "## Who comes after a squad, and in what.",
        "##",
        "## GENERATED by tools/extract_chasers.py from makechasers() in",
        "## src/combat/chase.cpp — do not edit by hand.",
        "##",
        '## The crowd is rolled as sitecrime / &"divisor" + 1, plus &"base",',
        '## capped at &"cap". The types are tried in order and the first whose',
        "## laws hold is the one that turns up.",
        "##",
        '## &"pullover" is whether the squad can surrender to them. Only the',
        "## police will take a surrender, and only while they are still police:",
        '## a responder marked &"no_surrender" takes it away again.',
        "",
        "",
        "## Site type -> who responds to trouble there.",
        "const BY_SITE: Dictionary = {",
    ]
    for site in sorted(responses):
        rule = responses[site]
        cars = ", ".join('&"%s"' % car for car in rule["cars"])
        types = []
        for entry in rule["types"]:
            parts = ['&"type": &"%s"' % entry["type"]]
            if entry.get("laws"):
                laws = ", ".join('[&"%s", &"%s", %s]' % (name.lower(), op, value)
                                 for name, op, value in entry["laws"])
                parts.append('&"laws": [%s]' % laws)
            if entry.get("no_surrender"):
                parts.append('&"no_surrender": true')
            types.append("{%s}" % ", ".join(parts))
        lines.append('\t&"%s": {&"cars": [%s], &"divisor": %d, &"base": %d, '
                     '&"cap": %d, &"pullover": %s, &"types": [%s]},'
                     % (site, cars, rule["divisor"], rule["base"], rule["cap"],
                        "true" if rule["pullover"] else "false",
                        ", ".join(types)))
    lines += ["}", ""]

    OUT.write_text("\n".join(lines))
    print("wrote %s: %d responses" % (OUT.relative_to(ROOT), len(responses)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
