#!/usr/bin/env python3
"""Generates game/core/site_plans.gd from initsite() in src/sitemode/sitemap.cpp.

Which floor plan a site gets is decided by two switch statements: the first
looks for a hand-drawn map exported as a pair of CSV files, and the second
falls back to a generated plan from art/sitemaps.txt. Both are read out of the
source rather than transcribed, because a site pointed at the wrong plan is the
kind of mistake that looks like working code.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "sitemode" / "sitemap.cpp"
DAILY = ROOT / "src" / "daily" / "daily.cpp"
OUT = ROOT / "game" / "core" / "site_plans.gd"


def switch_cases(body, call):
    """Reads a run of `case SITE_X:` labels ending in `call("VALUE")`.

    Labels stack, so several site types can share one map or plan.
    """
    found = {}
    pending = []
    for line in body.splitlines():
        for label in re.findall(r"case\s+(SITE_[A-Z0-9_]+)\s*:", line):
            pending.append(label)
        match = re.search(rf'{call}\("\s*([A-Za-z0-9_]+)\s*"', line)
        if match:
            for label in pending:
                found[label] = match.group(1)
            pending = []
        elif re.search(r"break\s*;", line):
            pending = []
    return found


def security():
    """How good a site's locks are, from securityable() in src/daily/daily.cpp.

    Zero is a place anyone can walk into, one is a respectable business, two is
    somewhere that expects to be broken into. The number decides how hard a
    lock is to pick and a door to kick in.
    """
    text = DAILY.read_text(errors="replace")
    body = text[text.index("char securityable(int type)"):]
    body = body[:body.index("\n}\n")]
    levels = {}
    pending = []
    for line in body.splitlines():
        for label in re.findall(r"case\s+(SITE_[A-Z0-9_]+)\s*:", line):
            pending.append(label)
        match = re.search(r"return\s+(\d+)\s*;", line)
        if match and pending:
            for label in pending:
                levels[label] = int(match.group(1))
            pending = []
    return levels


def key(label):
    """The site type as core/ids.gd names it: prefix off, lowercased."""
    return label.removeprefix("SITE_").lower()


def main() -> int:
    text = SOURCE.read_text(errors="replace")
    start = text.index("void initsite(Location &loc)")
    body = text[start:text.index("\n   //CLEAR AWAY BLOCKED DOORWAYS", start)]

    drawn = switch_cases(body, "readMap")
    generated = switch_cases(body, "build_site")
    locks = security()

    lines = [
        "class_name SitePlans",
        "extends RefCounted",
        "## Which floor plan each kind of site gets.",
        "##",
        "## GENERATED by tools/extract_site_plans.py from initsite() in",
        "## src/sitemode/sitemap.cpp — do not edit by hand.",
        "##",
        "## A site with a hand-drawn map uses it; anything else is generated from a",
        "## plan in core/site_maps.gd. A few types have neither and are built by the",
        "## fallback in core/systems/site/site_builder.gd.",
        "",
        "",
        "## Site type -> the name of its drawn plan in data/sitemaps/.",
        "const DRAWN: Dictionary = {",
    ]
    for site in sorted(drawn):
        lines.append(f'\t&"{key(site)}": &"{drawn[site]}",')
    lines += [
        "}",
        "",
        "",
        "## Site type -> the plan in core/site_maps.gd that generates it.",
        "const GENERATED: Dictionary = {",
    ]
    for site in sorted(generated):
        lines.append(f'\t&"{key(site)}": &"{generated[site]}",')
    lines += [
        "}",
        "",
        "",
        "## Site type -> how good its locks are: 1 a respectable business,",
        "## 2 somewhere that expects to be broken into. Anything absent is 0.",
        "const SECURITY: Dictionary = {",
    ]
    for site in sorted(locks):
        lines.append(f'\t&"{key(site)}": {locks[site]},')
    lines += ["}", ""]

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(drawn)} drawn, {len(generated)} generated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
