#!/usr/bin/env python3
"""Extracts the state-of-the-country sentences from src/basemode/liberalagenda.cpp.

The original's Liberal Agenda screen does not print "Abortion Rights: Moderate".
It prints a sentence saying what the country is actually like on that issue,
coloured by which way it has gone — "Women are second-class citizens.",
"Recreational drugs are prohibited unless medically prescribed.", "There are
open borders, and no distinctions between citizens and non-citizens." Twenty-two
laws, eight variants each: the five alignments, plus what the issue looks like
under each of the two ways the country can be lost and the one way the Elite
Liberal ending changes it.

That is a hundred and seventy-six sentences of the game's actual politics, and
the port had none of them. Lifting them mechanically is the only way to be sure.

The shape every case has, and which this refuses to guess at:

    case LAW_X:
       if(won==-2) ...                                    the Stalinist ending
       else if(won==-1) ...                               the corporate ending
       else if(law[l]==ALIGN_ARCHCONSERVATIVE) ...        -2
       else if(law[l]==-1) ...                            -1
       else if(law[l]==0) ...                              0
       else if(law[l]==1) ...                             +1
       else if(won!=1||wincondition!=WINCONDITION_ELITE)  +2
       else ...                                           the Elite ending
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "basemode" / "liberalagenda.cpp"
TARGET = ROOT / "game" / "data" / "agenda_lines.gd"

# The original's enum name for each law, against the idname the port knows it
# by. Order is the port's, from Ids.LAWS.
LAWS = [
    ("abortion", "LAW_ABORTION"),
    ("animalresearch", "LAW_ANIMALRESEARCH"),
    ("policebehavior", "LAW_POLICEBEHAVIOR"),
    ("privacy", "LAW_PRIVACY"),
    ("deathpenalty", "LAW_DEATHPENALTY"),
    ("nuclearpower", "LAW_NUCLEARPOWER"),
    ("pollution", "LAW_POLLUTION"),
    ("labor", "LAW_LABOR"),
    ("gay", "LAW_GAY"),
    ("corporate", "LAW_CORPORATE"),
    ("freespeech", "LAW_FREESPEECH"),
    ("flagburning", "LAW_FLAGBURNING"),
    ("guncontrol", "LAW_GUNCONTROL"),
    ("tax", "LAW_TAX"),
    ("women", "LAW_WOMEN"),
    ("civilrights", "LAW_CIVILRIGHTS"),
    ("drugs", "LAW_DRUGS"),
    ("immigration", "LAW_IMMIGRATION"),
    ("elections", "LAW_ELECTIONS"),
    ("military", "LAW_MILITARY"),
    ("prisons", "LAW_PRISONS"),
    ("torture", "LAW_TORTURE"),
]

# What each branch is called on this side, in the order the original tests them.
SLOTS = ["stalin", "corporate", "arch", "conservative", "moderate",
         "liberal", "elite_liberal", "elite"]


def case_body(text: str, enum_name: str) -> str:
    """The body of one case, up to its break."""
    start = re.search(rf"case {enum_name}:", text)
    if start is None:
        raise SystemExit(f"no case for {enum_name}")
    end = text.index("break;", start.end())
    return text[start.end():end]


def sentences(body: str, enum_name: str) -> list:
    """Every addstr() in the case, in source order."""
    found = re.findall(r'addstr\("((?:[^"\\]|\\.)*)"\)', body)
    if len(found) != len(SLOTS):
        raise SystemExit(
            f"{enum_name}: expected {len(SLOTS)} lines, found {len(found)}. "
            "The case does not have the shape this tool relies on; read it "
            "and fix the tool rather than the number.")
    return found


def gdscript(value: str) -> str:
    # The source escapes its own quotes; GDScript wants the same escaping, so
    # what is already \" stays \".
    return value


def main() -> int:
    text = SOURCE.read_bytes().decode("cp437")
    lines = [
        "class_name AgendaLines",
        "extends RefCounted",
        "## What the country is like on each issue, in the original's words.",
        "##",
        "## GENERATED by tools/extract_agenda.py from",
        "## src/basemode/liberalagenda.cpp. Do not edit by hand.",
        "##",
        "## Each law holds one sentence per alignment, plus the three the",
        "## endings replace them with: \"stalin\" and \"corporate\" for the two",
        "## ways the country is lost, \"elite\" for the Elite Liberal win.",
        "",
        "const LINES := {",
    ]
    count = 0
    for idname, enum_name in LAWS:
        said = sentences(case_body(text, enum_name), enum_name)
        lines.append(f'\t&"{idname}": {{')
        for slot, value in zip(SLOTS, said):
            lines.append(f'\t\t&"{slot}": "{gdscript(value)}",')
            count += 1
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}: "
          f"{len(LAWS)} laws, {count} sentences")
    return 0


if __name__ == "__main__":
    sys.exit(main())
