#!/usr/bin/env python3
"""Preserve the original site's dialogue tables, including response gestures."""
import json
import re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
s = (ROOT / 'src/sitemode/talk.cpp').read_text()

def block_at(start):
    start = s.index('{', start)
    # Braces inside these tables occur only outside their string literals.
    depth = 0
    for m in re.finditer(r'"(?:\\.|[^"\\])*"|[{}]', s[start:]):
        if m[0] == '{': depth += 1
        elif m[0] == '}':
            depth -= 1
            if depth == 0: return s[start+1:start+m.start()]
    raise ValueError('unterminated table')

def strings(body):
    return [json.loads(v) for v in re.findall(r'addstr\(("(?:\\.|[^"\\])*")\s*,\s*gamelog\)', body)]

def cases(body, numeric=True):
    pattern = r'case\s+(\d+)\s*:' if numeric else r'case\s+LAW_(\w+)\s*:'
    matches = list(re.finditer(pattern, body))
    return {int(m[1]) if numeric else m[1].lower(): strings(body[m.end():matches[i+1].start() if i+1<len(matches) else len(body)]) for i,m in enumerate(matches)}

def numeric_switches(start,end):
    return [cases(block_at(m.start())) for m in re.finditer(r'switch\((?:line|LCSrandom\(\d+\))\)', s) if start<=m.start()<end]

def join(parts):
    return ''.join(parts)

flirt_start=s.index('char doYouComeHereOften(Creature &a, Creature &tk)\n{')
issues_start=s.index('char talkAboutIssues(Creature &a, Creature &tk)\n{')
end=s.index('char talkInCombat(Creature &a, Creature &tk)\n{')
flirts=numeric_switches(flirt_start,issues_start)
assert [len(x) for x in flirts]==[3,47,3,8,3,47,3,47]
issues=[cases(block_at(m.start()),False) for m in re.finditer(r'switch\(lw\)',s) if issues_start<m.start()<end]
assert [len(x) for x in issues]==[22]*4
replies=numeric_switches(issues_start,end)
assert [len(x) for x in replies]==[10,10]
out=['class_name SiteDialogueTables','extends RefCounted','## GENERATED by tools/extract_site_dialogue.py from src/sitemode/talk.cpp.','## Original dialogue, kept separate from simulation and RNG.']
for name, table in zip(['FLIRT_CENSORED','FLIRT_LINES','DOG_REPLIES','MONSTER_REPLIES','FLIRT_ACCEPT_CENSORED','FLIRT_ACCEPT','FLIRT_REFUSE_CENSORED','FLIRT_REFUSE'],flirts):
    out.append('const '+name+' := '+json.dumps([join(table[i]) for i in range(len(table))],indent=1,ensure_ascii=False))
for name,table in zip(['FUMBLED','WON_ISSUE','ARGUMENT','COUNTERARGUMENT'],issues):
    # Conditional fragments are selected at render time, not concatenated.
    out.append('const '+name+' := '+json.dumps(table,indent=1,ensure_ascii=False))
for name,table in zip(['ACCEPT','REBUFF'],replies):
    out.append('const '+name+' := '+json.dumps([table[i] for i in range(10)],indent=1,ensure_ascii=False))
(ROOT/'game/data/site_dialogue_tables.gd').write_text('\n\n'.join(out)+'\n')
