#!/usr/bin/env python3
"""Lifts the original's character art out of art/*.cpc.

Three files, one format. Each is a 12-byte header — how many pictures, how
wide, how tall — followed by one cell after another, four bytes each: the
character, its foreground colour, its background colour, and whether it is
bold. loadgraphics() in src/news/news.cpp reads them exactly this way.

    largecap.cpc   27 letters, 5x7      the block capitals headlines are set in
    newstops.cpc    6 mastheads, 80x5   five newspapers and the Liberal Guardian
    newspic.cpc    13 pictures, 78x18   what runs beside a major event's story

This is the newspaper the port was missing. It had the words and none of the
paper: no masthead, no block-letter headline, no picture. All three are here,
in the repository, and have been the whole time.

The cells come across as base64 rather than as a list of numbers because
seventy thousand of them written out is a megabyte of GDScript that nothing
would ever read. [CharArt] decodes it and draws it.
"""
import base64
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "art"
TARGET = ROOT / "game" / "data" / "char_art.gd"

# What each file is, and what the port calls it.
FILES = [
    ("largecap.cpc", "CAPITALS",
     "The block capitals a headline is set in, A to Z and the apostrophe."),
    ("newstops.cpc", "MASTHEADS",
     "The five mainstream papers' mastheads, and the Liberal Guardian's."),
    ("newspic.cpc", "PICTURES",
     "The pictures that run beside a major event's story."),
]


def read(name: str):
    raw = (ART / name).read_bytes()
    count, wide, tall = struct.unpack("<iii", raw[:12])
    body = raw[12:]
    expected = count * wide * tall * 4
    if len(body) != expected:
        raise SystemExit(
            f"{name}: header says {count}x{wide}x{tall} ({expected} bytes) "
            f"but there are {len(body)}. The format is not what this assumes.")
    return count, wide, tall, body


def main() -> int:
    lines = [
        "class_name CharArt",
        "extends RefCounted",
        "## The original's character art, cell by cell.",
        "##",
        "## GENERATED by tools/extract_art.py from art/*.cpc. Do not edit.",
        "##",
        "## Each picture is [code]wide * tall[/code] cells in column-major",
        "## order, four bytes to a cell: the code page 437 character, the",
        "## foreground colour, the background colour, and whether it is bold.",
        "## The colours are the sixteen a DOS terminal had; [CharArtView]",
        "## turns them into the palette's own and draws the result.",
        "",
    ]
    for name, const, what in FILES:
        count, wide, tall, body = read(name)
        encoded = base64.b64encode(body).decode("ascii")
        lines.append(f"## {what}")
        lines.append(f"const {const} := {{")
        lines.append(f'\t"count": {count}, "wide": {wide}, "tall": {tall},')
        lines.append(f'\t"cells": "{encoded}",')
        lines.append("}")
        lines.append("")
        print(f"{name}: {count} pictures {wide}x{tall}, {len(body)} bytes")

    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} "
          f"({TARGET.stat().st_size // 1024}KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
