#!/usr/bin/env python3
"""Generates game/ui/adapters/title_quotes.gd from the original's title screen.

The title screen picks one of thirty-two quotations about disobeying the law.
They are the only writing in the game that is not about the game, and they are
worth keeping exactly.

    python3 tools/extract_quotes.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

HEADER = '''class_name TitleQuotes
extends RefCounted
## What the title screen says about breaking the law.
##
## GENERATED by tools/extract_quotes.py from src/title/titlescreen.cpp. The
## original prints one of these under the title every time it is shown, and
## draws to choose which — so the choice is [method pick], and the lines are
## the original's, em dash and all.

## Each quotation as its lines, the last of them the attribution.
const QUOTES: Array = [
'''

FOOTER = ''']


## One of them, chosen the way the original chooses.
static func pick(rng: Rng) -> Array:
	return QUOTES[rng.below(QUOTES.size())]
'''


def quotes() -> list[list[str]]:
    source = (ROOT / "src/title/titlescreen.cpp").read_bytes().decode("cp437")
    start = source.index("switch(LCSrandom(32))")
    opening = source.index("{", start)
    depth = 0
    end = opening
    while True:
        if source[end] == "{":
            depth += 1
        elif source[end] == "}":
            depth -= 1
            if depth == 0:
                break
        end += 1
    body = source[opening:end]
    found = []
    for case in re.split(r"\n\s*case \d+:", body)[1:]:
        lines = re.findall(r'strcpy\(str,"((?:[^"\\]|\\.)*)"\)', case)
        # The original writes the em dash as two box-drawing characters.
        found.append([line.replace('\\"', '"').replace("──", "—")
                      for line in lines])
    return found


def main() -> None:
    found = quotes()
    body = ""
    for lines in found:
        body += "\t[\n"
        for line in lines:
            body += '\t\t"%s",\n' % line.replace("\\", "\\\\").replace('"', '\\"')
        body += "\t],\n"
    out = ROOT / "game/ui/adapters/title_quotes.gd"
    out.write_text(HEADER + body + FOOTER)
    print("wrote %s: %d quotations" % (out, len(found)))


if __name__ == "__main__":
    main()
