#!/usr/bin/env python3
"""Generates game/data/places.gd from the original's place-name tables.

The newspaper picks a dateline for every story it prints and a state for the
execution story, and it picks them by index out of these two lists, so the
order is load-bearing in exactly the way names.gd's is.

    python3 tools/extract_places.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def cities() -> list[str]:
    # The original's sources are in the DOS codepage the game rendered with,
    # so an accented city name is one high byte rather than UTF-8.
    text = (ROOT / "src/common/getnames.cpp").read_bytes().decode("cp437")
    start = text.index("std::string cityname()")
    body = text[start:text.index("return pickrandom(city_names);", start)]
    # The table carries a long comment explaining how often each city is
    # listed, and puts two entries on one line where a city is listed twice.
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)
    body = re.sub(r"//[^\n]*", "", body)
    return re.findall(r'"([^"]*)"', body)


def states() -> list[str]:
    text = (ROOT / "src/common/misc.cpp").read_bytes().decode("cp437")
    start = text.index("const char* statename(int i)")
    body = text[start:text.index("\n}", start)]
    found = re.findall(r'case (\d+):\s*return "([^"]+)";', body)
    return [name for _, name in sorted(found, key=lambda pair: int(pair[0]))]


def quote(values: list[str]) -> str:
    return "".join('\t"%s",\n' % value.replace('"', '\\"') for value in values)


def main() -> None:
    city = cities()
    state = states()
    out = ROOT / "game/data/places.gd"
    out.write_text(
        'class_name Places\n'
        'extends RefCounted\n'
        '## Where a story is datelined from.\n'
        '##\n'
        '## GENERATED by tools/extract_places.py from src/common/getnames.cpp\n'
        '## and src/common/misc.cpp. Order is load-bearing: the newspaper picks\n'
        '## by index, so a list in a different order datelines a story from a\n'
        '## different place on the same seed.\n'
        '\n'
        '## %d entries, in source order. A city appears once per few hundred\n'
        '## thousand people who live in it, which is how the original weights\n'
        '## the pick.\n'
        'const CITIES: Array[String] = [\n%s]\n'
        '\n'
        '## The fifty states, in the original\'s order — which is alphabetical\n'
        '## except that it puts Arkansas before Arizona.\n'
        'const STATES: Array[String] = [\n%s]\n'
        % (len(city), quote(city), quote(state))
    )
    print("wrote %s: %d cities, %d states" % (out, len(city), len(state)))


if __name__ == "__main__":
    main()
