#!/usr/bin/env python3
"""Extracts the name lists from src/creature/creaturenames.cpp.

Six lists drive every name in the game. They are data, not code, so they belong
in data/ — and lifting them mechanically is the only way to be sure a
four-thousand-name transcription is exact.

Encoding: the source is not UTF-8 (it predates that being universal) and
carries accented names as single high bytes, in the code page a DOS terminal
draws with. Code page 437, not Latin-1 — the two disagree about exactly the
bytes these names use, and reading them as Latin-1 turns Jesus into "Jes£s",
Garcia into "Garc¡a" and Muller into "M\x81ller". Seventy-two of the four
thousand names came out mojibake, and they were drawn that way on the roster,
in the squad and in every line of news about the person.

An earlier version of this file said Latin-1 was deliberate, because it is
"what the trace harness's byte-wise escaping compares against". Whether that
was ever true, it is not load-bearing now: no golden trace in the project
contains a single one of these characters, because the traces name creature
types ("Political Activist") and the unnamed placeholder, never a generated
person. Checked before changing it.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "creature" / "creaturenames.cpp"
OUT = ROOT / "game" / "data" / "names"

LISTS = {
    "male_first_names": "male_first",
    "female_first_names": "female_first",
    "gender_neutral_first_names": "neutral_first",
    "great_white_male_patriarch_first_names": "patriarch_first",
    "regular_last_names": "regular_last",
    "archconservative_last_names": "archconservative_last",
}


def extract(text, name):
    match = re.search(rf'static const char \*{name}\[\] =\s*\{{(.*?)\n   \}};', text, re.S)
    if not match:
        raise SystemExit(f"list not found: {name}")
    return re.findall(r'"((?:[^"\\]|\\.)*)"', match.group(1))


def gdscript_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    text = SOURCE.read_bytes().decode("cp437")
    lines = [
        "class_name Names",
        "extends RefCounted",
        "## Every name the game can give someone.",
        "##",
        "## GENERATED by tools/extract_names.py from src/creature/creaturenames.cpp.",
        "## Order is load-bearing: names are chosen by index, so a list in a",
        "## different order produces a different person from the same seed.",
        "",
    ]
    counts = {}
    for source_name, gd_name in LISTS.items():
        values = extract(text, source_name)
        counts[gd_name] = len(values)
        lines.append(f"## {len(values)} entries, in source order.")
        lines.append(f"const {gd_name.upper()}: Array[String] = [")
        for value in values:
            lines.append(f'\t"{gdscript_escape(value)}",')
        lines.append("]")
        lines.append("")

    target = ROOT / "game" / "data" / "names.gd"
    target.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)}: " +
          ", ".join(f"{k}={v}" for k, v in counts.items()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
