#!/usr/bin/env python3
"""Extracts the world layout from src/locations/world.cpp.

make_classic_world() is written as a declarative block of District/Site macros —
it is a description of a city, not an algorithm — so it belongs in data/. This
lifts it rather than transcribing it, and fails if the macro shape changes.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "locations" / "world.cpp"
# Lives in core/ rather than data/ because it is a table with an accessor,
# like core/tables.gd; data/ holds content resources with no behaviour.
OUT = ROOT / "game" / "core" / "world_layout.gd"

PROPERTY_NAMES = {
    "renting": "renting",
    "hidden": "hidden",
    "mapped": "mapped",
    "upgradable": "upgradable",
}


def value_of(raw: str) -> str:
    raw = raw.strip()
    if raw in ("true", "false"):
        return raw
    if raw == "hasmaps":
        return "has_maps"
    if raw.startswith("RENTING_"):
        return f"Renting.{raw.removeprefix('RENTING_')}"
    raise SystemExit(f"unhandled property value: {raw}")


def main() -> int:
    text = SOURCE.read_text(errors="replace")
    body = re.search(r"void make_classic_world\(bool hasmaps\)\s*\{(.*?)\n\}", text, re.S)
    if not body:
        raise SystemExit("make_classic_world not found")

    districts = []
    current = None
    target = None
    for line in body.group(1).splitlines():
        line = re.sub(r"//.*", "", line).strip()
        if not line:
            continue
        district = re.fullmatch(r"District\((\w+), (\d+)\)", line)
        if district:
            current = {"type": district.group(1).removeprefix("SITE_").lower(),
                       "area": int(district.group(2)), "properties": {}, "sites": []}
            districts.append(current)
            target = current
            continue
        site = re.fullmatch(r"Site\((\w+)\)", line)
        if site:
            target = {"type": site.group(1).removeprefix("SITE_").lower(), "properties": {}}
            current["sites"].append(target)
            continue
        prop = re.fullmatch(r"(?:District|Site)Property\((\w+), (.+)\)", line)
        if prop:
            name = PROPERTY_NAMES.get(prop.group(1))
            if name is None:
                raise SystemExit(f"unhandled property: {prop.group(1)}")
            target["properties"][name] = value_of(prop.group(2))
            continue
        if line.startswith(("Location*", "int id", "id =")):
            continue
        raise SystemExit(f"unrecognised line in make_classic_world: {line}")

    lines = [
        "class_name WorldLayout",
        "extends RefCounted",
        "## The shape of a city: its districts and what stands in each.",
        "##",
        "## GENERATED by tools/extract_world.py from make_classic_world() in",
        "## src/locations/world.cpp, which is written as a declarative block of",
        "## macros — a description of a city, not an algorithm.",
        "##",
        "## Order is load-bearing: locations are numbered as they are created, and",
        "## those ids are what everything else refers to.",
        "",
        "",
        "## Districts in order, each with the sites it contains.",
        "static func districts(has_maps: bool) -> Array:",
        "\treturn [",
    ]
    for district in districts:
        lines.append("\t\t{")
        lines.append(f'\t\t\t"type": &"{district["type"]}",')
        lines.append(f'\t\t\t"area": {district["area"]},')
        lines.append(f'\t\t\t"properties": {{{_props(district["properties"])}}},')
        lines.append('\t\t\t"sites": [')
        for site in district["sites"]:
            lines.append('\t\t\t\t{"type": &"%s", "properties": {%s}},'
                         % (site["type"], _props(site["properties"])))
        lines.append("\t\t\t],")
        lines.append("\t\t},")
    lines += ["\t]", ""]

    OUT.write_text("\n".join(lines))
    site_count = sum(len(d["sites"]) for d in districts)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(districts)} districts, {site_count} sites")
    return 0


def _props(properties: dict) -> str:
    return ", ".join(f'&"{name}": {value}' for name, value in properties.items())


if __name__ == "__main__":
    sys.exit(main())
