#!/usr/bin/env python3
"""Generates game/core/ids.gd from the C++ enums.

The trace harness records attributes, skills, laws and public views as bare
arrays, so the port must agree with the original on the *order* of every one of
them. Deriving the names from the source removes the chance of a hand-copied
list drifting; run this whenever the enums change.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "game" / "core" / "ids.gd"

# (GDScript group name, source file, enum name, prefix to strip, terminator)
ENUMS = [
    ("ATTRIBUTES", "src/creature/creature.h", "CreatureAttribute", "ATTRIBUTE_", "ATTNUM"),
    ("SKILLS", "src/creature/creature.h", "CreatureSkill", "SKILL_", "SKILLNUM"),
    ("BODY_PARTS", "src/creature/creature.h", "Bodyparts", "BODYPART_", "BODYPARTNUM"),
    ("SPECIAL_WOUNDS", "src/creature/creature.h", "SpecialWounds", "SPECIALWOUND_", "SPECIALWOUNDNUM"),
    ("LAWS", "src/includes.h", "Laws", "LAW_", "LAWNUM"),
    ("VIEWS", "src/includes.h", "Views", "VIEW_", "VIEWNUM"),
    ("ACTIVITIES", "src/includes.h", "Activity", "ACTIVITY_", "ACTIVITYNUM"),
]


def members(source: str, enum_name: str, prefix: str, terminator: str):
    """Returns the enum's non-negative members, lowercased and prefix-stripped.

    Several of these enums open with pseudo-members at -2 and -1 (the original
    computes those views from the real ones), so member values are tracked and
    anything below zero is left out — it has no slot in the arrays the traces
    record.
    """
    text = (ROOT / source).read_text(errors="replace")
    match = re.search(rf"enum\s+{enum_name}\s*\{{(.*?)\}};", text, re.S)
    if not match:
        raise SystemExit(f"enum {enum_name} not found in {source}")

    names = []
    value = 0
    for line in match.group(1).splitlines():
        line = re.sub(r"//.*|/\*.*?\*/", "", line).strip()
        for part in line.split(","):
            part = part.strip()
            if not part:
                continue
            name, _, assigned = part.partition("=")
            name = name.strip()
            if not re.fullmatch(r"[A-Z_][A-Z0-9_]*", name):
                continue
            if name == terminator:
                return names
            if assigned.strip():
                try:
                    value = int(assigned.strip(), 0)
                except ValueError:
                    raise SystemExit(f"{enum_name}: cannot read value of {name}")
            if value >= 0:
                if len(names) != value:
                    raise SystemExit(
                        f"{enum_name}: {name} is {value} but would land at index {len(names)}")
                names.append(name.removeprefix(prefix).lower())
            value += 1
    return names


def skill_attributes(skills):
    """Parses Skill::get_associated_attribute() into a skill -> attribute map.

    The switch falls through case labels, so a run of labels shares the
    attribute the run ends with; anything not listed falls to the default.
    """
    text = (ROOT / "src/creature/creature.cpp").read_text(errors="replace")
    match = re.search(r"CreatureAttribute Skill::get_associated_attribute[^{]*\{(.*?)\n\}",
                      text, re.S)
    if not match:
        raise SystemExit("get_associated_attribute not found")

    mapping = {}
    pending = []
    default = None
    for line in match.group(1).splitlines():
        line = re.sub(r"//.*", "", line).strip()
        case = re.fullmatch(r"case SKILL_([A-Z0-9_]+):", line)
        if case:
            pending.append(case.group(1).lower())
            continue
        if line == "default:":
            pending.append(None)
            continue
        returned = re.fullmatch(r"return ATTRIBUTE_([A-Z0-9_]+);", line)
        if returned:
            attribute = returned.group(1).lower()
            for skill in pending:
                if skill is None:
                    default = attribute
                else:
                    mapping[skill] = attribute
            pending = []
    if default is None:
        raise SystemExit("get_associated_attribute has no default branch")

    missing = [skill for skill in skills if skill not in mapping]
    for skill in missing:
        mapping[skill] = default
    return mapping


def main() -> int:
    groups = [(name, members(source, enum_name, prefix, terminator))
              for name, source, enum_name, prefix, terminator in ENUMS]

    lines = [
        "class_name Ids",
        "extends RefCounted",
        "## Every identifier the simulation names, in the original's order.",
        "##",
        "## GENERATED by tools/generate_ids.py from the C++ enums — do not edit by",
        "## hand. Order is load-bearing: the golden traces record attributes, skills,",
        "## laws and public views as bare arrays indexed by these enums, so a list out",
        "## of order silently breaks every parity comparison.",
        "##",
        "## Systems refer to these constants and never to bare strings, so renaming a",
        "## skill is one edit here plus a regeneration.",
        "",
    ]
    for name, values in groups:
        lines.append(f"## {len(values)} entries, in enum order.")
        lines.append(f"const {name}: Array[StringName] = [")
        for value in values:
            lines.append(f'\t&"{value}",')
        lines.append("]")
        lines.append("")

    skills = dict(groups)["SKILLS"]
    mapping = skill_attributes(skills)
    lines.append("## The attribute that caps each skill, from")
    lines.append("## Skill::get_associated_attribute() in the original.")
    lines.append("const SKILL_ATTRIBUTE: Dictionary = {")
    for skill in skills:
        lines.append(f'\t&"{skill}": &"{mapping[skill]}",')
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}: " +
          ", ".join(f"{name}={len(values)}" for name, values in groups))
    return 0


if __name__ == "__main__":
    sys.exit(main())
